// The DC roster's pages: suit, setting, poses and script, one entry per theme in
// src/renderer/js/00-dc-themes.js (ids match, which is how the app finds a page).
//
// Same rules as heroes.js: the script is original and about git — pages *in the style of*
// the books, not copies of any of them. Suit keys are documented in heroes.js and figure.js.
'use strict';
const { SKIN, base } = require('./heroes');

const INK = '#17120f';
const GOTHAM = { time: 'night', rainy: true };

const DC_HEROES = [
  // ---------------- Heroes ----------------
  base({
    id: 'dc-batman', name: 'Batman', settingOpts: GOTHAM, layout: 1,
    accent: '#4a5262', secondary: '#1a1e28', symbol: 'batoval', symbolColor: INK, sfxFill: '#ffe14a', sfxRim: '#1a1e28',
    suit: { head: { type: 'cowl', mask: '#3a3f4c', eyes: 'white', ears: true }, torso: '#5a6272', arms: '#5a6272', gloves: '#1e222c', legs: '#5a6272', boots: '#1e222c', belt: '#e0b83a', cape: '#1e222c', emblem: 'bat', emblemColor: INK, bulk: 1.2 },
    poses: { establish: 'crouch', hero: 'stand', action: 'punch', quiet: 'crouch', finale: 'stand' },
    lines: {
      caption: 'Gotham. 3 a.m. Somebody pushed straight to main.',
      closeup: 'I already ran git blame. I know who you are.',
      hero: ['I am vengeance.', 'I am the night. I am code review.'],
      sfx: 'KRAKK!', quiet: 'He keeps a reflog on every criminal in the city.',
      emblem: 'BLAMED', finale: 'Not the hero this repo deserves. The one it needs.',
    },
  }),
  base({
    id: 'dc-superman', name: 'Superman', settingOpts: { time: 'day' }, layout: 0,
    accent: '#2f5fc0', secondary: '#c8303a', symbol: 'super', symbolColor: '#f0c840',
    suit: { head: { hair: 'short', hairColor: '#141820', eyes: 'plain', jaw: 1.1 }, torso: '#2f5fc0', arms: '#2f5fc0', gloves: '#2f5fc0', legs: '#2f5fc0', boots: '#c8303a', belt: '#f0c840', cape: '#c8303a', emblem: 'super', emblemColor: '#f0c840', bulk: 1.25 },
    poses: { establish: 'fly', hero: 'hips', action: 'fly', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Metropolis. Faster than a speeding fast-forward.',
      closeup: 'Is it a bird? Is it a plane? It\'s a clean merge.',
      hero: ['Truth. Justice.', 'And a linear history.'],
      sfx: 'WHOOOSH!', quiet: 'Glasses on, he\'s just a mild-mannered reviewer who approves everything.',
      emblem: 'HOPE', finale: 'Up, up and away — after the tests pass.',
    },
  }),
  base({
    id: 'dc-wonderwoman', name: 'Wonder Woman', setting: 'island', layout: 2,
    accent: '#b8283a', secondary: '#2a4aa8', symbol: 'ww', symbolColor: '#f0c040',
    suit: { head: { hair: 'long', hairColor: '#141010', eyes: 'plain', tiara: '#f0c040' }, torso: '#b8283a', lower: '#2a4aa8', arms: SKIN.light, gloves: '#d8d8e0', legs: SKIN.light, boots: '#b8283a', tallBoots: true, belt: '#f0c040', emblem: 'ww', emblemColor: '#f0c040', prop: 'lasso', waist: 0.6 },
    poses: { establish: 'leap', hero: 'stand', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Themyscira. An island where every commit message tells the truth.',
      closeup: 'Bound by the lasso, the history cannot lie.',
      hero: ['"fixed stuff"?', 'Tell me what you really changed.'],
      sfx: 'SHWAKK!', quiet: 'The lasso compels honesty. Even from a squash.',
      emblem: 'TRUTH', finale: 'I will fight for those who cannot write their own changelog.',
    },
  }),
  base({
    id: 'dc-flash', name: 'The Flash', settingOpts: { time: 'dusk' }, layout: 3,
    accent: '#c8282e', secondary: '#f0c43a', symbol: 'flash', symbolColor: '#f0c43a', sfxFill: '#fff0a0', sfxRim: '#c8282e',
    suit: { head: { mask: '#c8282e', eyes: 'white', type: 'cowl', wings: '#f0c43a' }, torso: '#c8282e', arms: '#c8282e', gloves: '#c8282e', legs: '#c8282e', boots: '#f0c43a', belt: '#f0c43a', emblem: 'flash', emblemColor: '#f0c43a', waist: 0.66 },
    poses: { establish: 'leap', hero: 'punch', action: 'leap', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Central City. The CI pipeline takes forty minutes. He doesn\'t.',
      closeup: 'I ran the whole test suite while you were reading this.',
      hero: ['Fastest man alive.', 'Slowest build on Earth.'],
      sfx: 'ZWOOOM!', quiet: 'He went back in time to fix one typo. Now there are three timelines.',
      emblem: 'FAST', finale: 'Never rewrite history. Trust me. I\'ve tried.',
    },
  }),
  base({
    id: 'dc-greenlantern', name: 'Green Lantern', setting: 'space', settingOpts: { tint: '#2a9a50', planet: '#5ad07a' }, layout: 0,
    accent: '#2a9a50', secondary: '#141a16', symbol: 'lantern', symbolColor: '#6aff9a', sfxFill: '#aaffc0', sfxRim: '#145a2a',
    suit: { head: { hair: 'short', hairColor: '#4a3020', eyes: 'plain', bandana: '#1a2a1e' }, torso: '#1a2a1e', sides: '#2a9a50', arms: '#1a2a1e', gloves: '#e8ece8', legs: '#2a9a50', boots: '#2a9a50', emblem: 'lantern', emblemColor: '#6aff9a', handGlow: '#6aff9a', aura: ['#6aff9a', '#d8ffe4'] },
    poses: { establish: 'fly', hero: 'cast', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Sector 2814. The ring can make anything he imagines. He imagines a pipeline.',
      closeup: 'In brightest day, in blackest night…',
      hero: ['No bug shall', 'escape my sight!'],
      sfx: 'VWOOMM!', quiet: 'Willpower: the only thing that gets a monorepo to build.',
      emblem: 'WILL', finale: 'Let those who worship evil\'s might beware my power — git bisect\'s light!',
    },
  }),
  base({
    id: 'dc-aquaman', name: 'Aquaman', setting: 'sea', layout: 1,
    accent: '#e0902c', secondary: '#2a8a5a', symbol: 'ring', symbolColor: '#f0c040',
    suit: { head: { hair: 'long', hairColor: '#e0b850', eyes: 'plain' }, torso: '#e0902c', arms: '#2a8a5a', gloves: '#2a8a5a', legs: '#2a8a5a', boots: '#2a8a5a', belt: '#f0c040', prop: 'trident', bulk: 1.2 },
    poses: { establish: 'leap', hero: 'stand', action: 'punch', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'The Atlantic. Twenty thousand leagues of submodules.',
      closeup: 'Everyone laughs until they need a deep clone.',
      hero: ['I command the', 'depths of this history!'],
      sfx: 'SPLASSHH!', quiet: 'He talks to fish. The fish say: fetch with --depth 1.',
      emblem: 'DEEP', finale: 'The sea keeps every object. So does .git.',
    },
  }),
  base({
    id: 'dc-cyborg', name: 'Cyborg', setting: 'lab', settingOpts: { glow: '#ff3a44' }, layout: 2,
    accent: '#b8c0cc', secondary: '#3a4250', symbol: 'gem', symbolColor: '#ff3a44', sfxFill: '#ffb0b0', sfxRim: '#3a4250',
    suit: { skin: SKIN.brown, head: { mask: SKIN.brown, half: '#b8c0cc', eyes: 'plain' }, torso: '#b8c0cc', sides: '#5a6270', arms: '#b8c0cc', gloves: '#5a6270', legs: '#b8c0cc', boots: '#5a6270', emblem: 'gem', emblemColor: '#ff3a44', handGlow: '#ff6a6a', bulk: 1.3 },
    poses: { establish: 'stand', hero: 'hips', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'S.T.A.R. Labs. Half man, half machine, all webhooks.',
      closeup: 'Booyah. Connected to every remote on the planet.',
      hero: ['I don\'t clone repos.', 'I AM the remote.'],
      sfx: 'BZZRRT!', quiet: 'He reads the Git protocol natively. It is mostly "have" and "want".',
      emblem: 'SYNCED', finale: 'Fetch, merge, push. My heart is a pre-commit hook.',
    },
  }),
  base({
    id: 'dc-martian', name: 'Martian Manhunter', setting: 'space', settingOpts: { tint: '#c84a2a', planet: '#d8603a' }, layout: 3,
    accent: '#3a9a50', secondary: '#c83030', symbol: 'ring', symbolColor: '#c83030', sfxFill: '#b8ffc8', sfxRim: '#c83030',
    suit: { skin: '#4aa05a', head: { mask: '#4aa05a', eyes: 'glow', eyeColor: '#ff6a3a', brow: INK, jaw: 1.15 }, torso: '#4aa05a', arms: '#4aa05a', gloves: '#4aa05a', legs: '#2a3a8a', boots: '#2a3a8a', cape: '#2a3a8a', xStraps: '#c83030', belt: '#c83030', bulk: 1.2 },
    poses: { establish: 'fly', hero: 'stand', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Mars, long ago. Then Earth, and a repository he can read like a mind.',
      closeup: 'I sense your intent. You meant to commit only one file.',
      hero: ['I phase through', 'the conflict markers.'],
      sfx: 'VMMMMM!', quiet: 'He can shapeshift into any author. Signed commits stop him cold.',
      emblem: 'PHASED', finale: 'On my world, every change was reviewed telepathically.',
    },
  }),
  base({
    id: 'dc-greenarrow', name: 'Green Arrow', setting: 'forest', layout: 0,
    accent: '#3a7a3a', secondary: '#d8c070', symbol: 'ring', symbolColor: '#d8c070',
    suit: { head: { hair: 'short', hairColor: '#d8b050', eyes: 'plain', bandana: '#2a5a2a', hood: '#3a7a3a', jaw: 1.05 }, torso: '#3a7a3a', arms: '#3a7a3a', gloves: '#2a4a2a', legs: '#2a4a2a', boots: '#2a3a2a', belt: '#5a4a2a', prop: 'bow' },
    poses: { establish: 'crouch', hero: 'stand', action: 'cast', quiet: 'crouch', finale: 'hips' },
    lines: {
      caption: 'Star City. One quiver, a dozen trick arrows, one bad merge.',
      closeup: 'You have failed this codebase.',
      hero: ['Boxing-glove arrow:', 'git reset --soft.'],
      sfx: 'THWOKK!', quiet: 'Net arrow: catches everything in the staging area.',
      emblem: 'TARGETED', finale: 'Robin Hood stole from the rich. I steal from main.',
    },
  }),
  base({
    id: 'dc-blackcanary', name: 'Black Canary', settingOpts: { time: 'night' }, layout: 1,
    accent: '#2a2a32', secondary: '#4ab0d8', symbol: 'ring', symbolColor: '#7fd0f0', sfxFill: '#cff4ff', sfxRim: '#2a6a8a',
    suit: { head: { hair: 'long', hairColor: '#f0d878', eyes: 'plain' }, torso: '#24242c', arms: '#24242c', gloves: '#24242c', legs: '#3a3a44', boots: '#1a1a20', waist: 0.6, bulk: 0.92 },
    poses: { establish: 'stand', hero: 'cast', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Gotham\'s birds of prey nest above an unresolved conflict.',
      closeup: 'Stand back. This is going to be loud.',
      hero: ['CONFLICT', 'MARKERS — GONE!'],
      sfx: 'SKREEEEE!', quiet: 'One canary cry deletes every <<<<<<< in a block radius.',
      emblem: 'SONIC', finale: 'Some resolve conflicts patiently. I resolve them at 140 decibels.',
    },
  }),
  base({
    id: 'dc-shazam', name: 'Shazam', setting: 'storm', settingOpts: { glow: '#f0c840' }, layout: 2,
    accent: '#c8302a', secondary: '#f0c840', symbol: 'bolt', symbolColor: '#f0c840', sfxFill: '#fff4a0', sfxRim: '#c8302a',
    suit: { head: { hair: 'short', hairColor: '#141010', eyes: 'plain' }, torso: '#c8302a', arms: '#c8302a', gloves: '#f0c840', legs: '#c8302a', boots: '#f0c840', belt: '#f0c840', cape: '#f4f0e4', emblem: 'bolt', emblemColor: '#f0c840', bulk: 1.3 },
    poses: { establish: 'fly', hero: 'hips', action: 'punch', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Philadelphia. A kid says one word and becomes a senior engineer.',
      closeup: 'Wait — I have admin rights now?',
      hero: ['SHAZAM!', 'Okay, what does rebase -i do?'],
      sfx: 'KRA-KOOM!', quiet: 'The wisdom of Solomon. The force-push of Hercules. Dangerous combo.',
      emblem: 'SHAZAM', finale: 'With one word, every junior becomes a maintainer. Mostly by accident.',
    },
  }),
  base({
    id: 'dc-nightwing', name: 'Nightwing', settingOpts: { time: 'night' }, layout: 3,
    accent: '#3a8ae0', secondary: '#141820', symbol: 'nightwing', symbolColor: '#3a8ae0', sfxFill: '#bfe4ff', sfxRim: '#1a3a6a',
    suit: { head: { hair: 'short', hairColor: '#141010', eyes: 'plain', bandana: '#141820' }, torso: '#1a1e28', arms: '#1a1e28', gloves: '#1a1e28', legs: '#1a1e28', boots: '#1a1e28', emblem: 'nightwing', emblemColor: '#3a8ae0', prop: 'escrima', waist: 0.64 },
    poses: { establish: 'leap', hero: 'crouch', action: 'leap', quiet: 'crouch', finale: 'stand' },
    lines: {
      caption: 'Blüdhaven. He forked from the family repo and never looked back.',
      closeup: 'Same codebase. My branch now.',
      hero: ['Acrobatics?', 'I call it cherry-picking.'],
      sfx: 'THWAKK!', quiet: 'He still rebases onto the old man\'s main every Sunday.',
      emblem: 'FORKED', finale: 'Every fork keeps its upstream. That\'s family.',
    },
  }),
  base({
    id: 'dc-robin', name: 'Robin', settingOpts: GOTHAM, layout: 0,
    accent: '#c8302a', secondary: '#2a7a3a', symbol: 'R', symbolColor: '#f0c840',
    suit: { head: { hair: 'short', hairColor: '#141010', eyes: 'plain', bandana: INK }, torso: '#c8302a', arms: '#2a7a3a', gloves: '#2a7a3a', legs: '#2a2a30', boots: '#1a1a20', belt: '#f0c840', cape: '#f0c840', emblem: 'R', emblemColor: '#f0c840', prop: 'staff', bulk: 0.9 },
    poses: { establish: 'leap', hero: 'stand', action: 'punch', quiet: 'crouch', finale: 'hips' },
    lines: {
      caption: 'The Batcave. The newest contributor reads the whole history on day one.',
      closeup: 'Holy merge conflict!',
      hero: ['I\'m not a sidekick.', 'I\'m a co-author.'],
      sfx: 'POW!', quiet: 'Co-authored-by: Robin. It\'s in the trailer, so it\'s official.',
      emblem: 'CO-AUTHOR', finale: 'Every Batman needs a second reviewer.',
    },
  }),
  base({
    id: 'dc-batgirl', name: 'Batgirl', settingOpts: GOTHAM, layout: 1,
    accent: '#5a4a8a', secondary: '#f0c840', symbol: 'bat', symbolColor: '#f0c840', sfxRim: '#3a2a6a',
    suit: { head: { type: 'cowl', mask: '#4a3a7a', eyes: 'plain', ears: true, hair: 'long', hairColor: '#c8402a' }, torso: '#4a3a7a', arms: '#4a3a7a', gloves: '#f0c840', legs: '#4a3a7a', boots: '#f0c840', belt: '#f0c840', cape: '#3a2a6a', emblem: 'bat', emblemColor: '#f0c840', waist: 0.6, bulk: 0.92 },
    poses: { establish: 'crouch', hero: 'stand', action: 'leap', quiet: 'crouch', finale: 'hips' },
    lines: {
      caption: 'Gotham. By night a hero; by day she runs the whole infrastructure.',
      closeup: 'Oracle here. I see every branch in this city.',
      hero: ['Twelve monitors.', 'Twelve open pull requests.'],
      sfx: 'WHAPP!', quiet: 'She wrote the CI config. Nobody else is allowed to touch it.',
      emblem: 'ORACLE', finale: 'Information is power. Logs are information.',
    },
  }),
  base({
    id: 'dc-supergirl', name: 'Supergirl', setting: 'ice', layout: 2,
    accent: '#3a6ad0', secondary: '#e0303a', symbol: 'super', symbolColor: '#f0c840',
    suit: { head: { hair: 'long', hairColor: '#f0d070', eyes: 'plain' }, torso: '#3a6ad0', lower: '#e0303a', arms: '#3a6ad0', gloves: '#3a6ad0', legs: '#3a6ad0', boots: '#e0303a', tallBoots: true, belt: '#f0c840', cape: '#e0303a', emblem: 'super', emblemColor: '#f0c840', waist: 0.6, bulk: 0.95 },
    poses: { establish: 'fly', hero: 'fly', action: 'punch', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'The Fortress of Solitude. Every Kryptonian archive, mirrored.',
      closeup: 'Krypton is gone. The backups aren\'t.',
      hero: ['I was sent', 'to protect the history.'],
      sfx: 'FWOOSH!', quiet: 'A whole world lost because nobody pushed. She never forgets that.',
      emblem: 'BACKED UP', finale: 'A remote on another planet. That\'s a real backup strategy.',
    },
  }),
  base({
    id: 'dc-hawkman', name: 'Hawkman', setting: 'canyon', layout: 3,
    accent: '#6aa04a', secondary: '#d8a040', symbol: 'hawk', symbolColor: '#d8a040',
    suit: { head: { mask: '#d8a040', eyes: 'plain', helm: '#d8a040', mouth: true }, torso: SKIN.light, arms: SKIN.light, gloves: '#d8a040', legs: '#3a6a2a', boots: '#d8a040', tallBoots: true, belt: '#8a5a2a', xStraps: '#8a5a2a', wings: 'mech', wingColor: '#c89040', prop: 'mace', bulk: 1.3, abs: true },
    poses: { establish: 'fly', hero: 'stand', action: 'punch', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Thanagar, Egypt, America. He has been reincarnated more times than this branch.',
      closeup: 'I remember every past life. And every past commit.',
      hero: ['Nth metal mace.', 'Nth attempt at this rebase.'],
      sfx: 'KRUNCH!', quiet: 'History repeats. He has the reflog to prove it.',
      emblem: 'REBORN', finale: 'Death is just a detached HEAD.',
    },
  }),
  base({
    id: 'dc-zatanna', name: 'Zatanna', setting: 'mystic', settingOpts: { glow: '#e8d8ff', tint: '#2a1a4a' }, layout: 0,
    accent: '#2a2a34', secondary: '#d03040', symbol: 'gem', symbolColor: '#fff2b0', sfxFill: '#e8d8ff', sfxRim: '#5a2a8a',
    suit: { head: { hair: 'long', hairColor: '#141010', eyes: 'plain', hat: 'top', hatColor: '#1a1a20', hatBand: '#d03040' }, torso: '#1a1a20', vest: '#f4f4f8', arms: '#1a1a20', gloves: '#f4f4f8', legs: '#2a2a30', boots: '#1a1a20', prop: 'wand', handGlow: '#fff2b0', waist: 0.6, bulk: 0.9 },
    poses: { establish: 'cast', hero: 'cast', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'The Shadowcrest stage. Tonight\'s trick: making a merge conflict disappear.',
      closeup: 'Nothing up my sleeve but a stash.',
      hero: ['!raeppasid ,tcilfnoC', '!egrem naelc a ekaM'],
      sfx: '!FOOP', quiet: 'She spells every command backwards. The shell has no idea.',
      emblem: '!CIGAM', finale: '!hsup tig — and the crowd goes wild.',
    },
  }),
  base({
    id: 'dc-bluebeetle', name: 'Blue Beetle', settingOpts: { time: 'dusk' }, layout: 1,
    accent: '#2a6ad0', secondary: '#141a28', symbol: 'scarab', symbolColor: '#3a8ae0', sfxFill: '#bfe0ff', sfxRim: '#1a3a7a',
    suit: { head: { mask: '#2a6ad0', eyes: 'lens-big', lens: '#e8b040' }, torso: '#2a6ad0', sides: '#141a28', arms: '#2a6ad0', gloves: '#141a28', legs: '#141a28', boots: '#2a6ad0', emblem: 'scarab', emblemColor: '#3a8ae0', wings: 'insect', wingColor: '#7fb8ff', handGlow: '#7fc0ff' },
    poses: { establish: 'fly', hero: 'stand', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'El Paso. An alien scarab bonded to a teenager. Now it reviews his code.',
      closeup: 'Khaji Da says my variable names are "unacceptable."',
      hero: ['The scarab wants', 'to delete the tests!'],
      sfx: 'BZZOWW!', quiet: 'Built-in linter. Very loud. Fused to his spine.',
      emblem: 'LINTED', finale: 'Family first. Then formatting.',
    },
  }),
  base({
    id: 'dc-starfire', name: 'Starfire', setting: 'space', settingOpts: { tint: '#e07a2a', planet: '#c84aa0' }, layout: 2,
    accent: '#7a3aa0', secondary: '#5ad050', symbol: 'gem', symbolColor: '#6aff6a', sfxFill: '#c8ffb0', sfxRim: '#4a1a6a',
    suit: { skin: '#e8a050', head: { hair: 'long', hairColor: '#e0402a', eyes: 'white' }, torso: '#7a3aa0', arms: '#e8a050', gloves: '#7a3aa0', legs: '#e8a050', boots: '#7a3aa0', tallBoots: true, belt: '#c0c8d0', emblem: 'gem', emblemColor: '#6aff6a', handGlow: '#6aff6a', waist: 0.58, bulk: 0.92 },
    poses: { establish: 'fly', hero: 'fly', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Tamaran, then Titans Tower. Learning Earth\'s strange customs. And git.',
      closeup: 'On my planet we do not "squash." It is rude.',
      hero: ['Why is "HEAD" detached?', 'Is it in pain?'],
      sfx: 'ZRAKKK!', quiet: 'Starbolts powered by joy. CI powered by spite.',
      emblem: 'JOY', finale: 'I have learned your customs. Now: git commit --amend!',
    },
  }),
  base({
    id: 'dc-raven', name: 'Raven', setting: 'mystic', settingOpts: { glow: '#b89aff', tint: '#1a0a2a' }, layout: 3,
    accent: '#4a3a8a', secondary: '#d02840', symbol: 'gem', symbolColor: '#d02840', sfxFill: '#d8c8ff', sfxRim: '#1a0a2a',
    suit: { head: { hood: '#2a1e4a', eyes: 'white', mask: '#c8b8d8', mouth: true }, skin: '#c8b8d8', torso: '#1a1a24', arms: '#1a1a24', gloves: '#1a1a24', legs: '#1a1a24', boots: '#2a1e4a', cape: '#2a1e4a', emblem: 'gem', emblemColor: '#d02840', handGlow: '#b89aff', waist: 0.6, bulk: 0.88 },
    poses: { establish: 'cast', hero: 'cast', action: 'cast', quiet: 'stand', finale: 'stand' },
    lines: {
      caption: 'Azarath. Calm is the only thing that holds the darkness back. And code review.',
      closeup: 'Azarath. Metrion. Zinthos.',
      hero: ['My emotions', 'are not a merge strategy.'],
      sfx: 'SHHHRAAA!', quiet: 'She meditates through every flaky test. It does not help.',
      emblem: 'ZINTHOS', finale: 'The darkness is in the commit history. I let it stay there.',
    },
  }),
  base({
    id: 'dc-cosmicboy', name: 'Cosmic Boy', setting: 'space', settingOpts: { tint: '#d04a9a', planet: '#8a8a98' }, layout: 0,
    accent: '#d04a9a', secondary: '#1a1a24', symbol: 'legion', symbolColor: '#f0c840', sfxFill: '#ffc8e8', sfxRim: '#5a1a4a',
    suit: { head: { hair: 'short', hairColor: '#141010', eyes: 'plain' }, torso: '#1a1a24', sides: '#d04a9a', arms: '#1a1a24', gloves: '#d04a9a', legs: '#1a1a24', boots: '#d04a9a', belt: '#d04a9a', emblem: 'legion', emblemColor: '#f0c840', handGlow: '#ff8ad0' },
    poses: { establish: 'fly', hero: 'cast', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'The 31st century. The Legion still uses git. Some things are forever.',
      closeup: 'Long live the Legion! And long live main.',
      hero: ['Magnetism:', 'every ref pulled into line.'],
      sfx: 'VRRANNG!', quiet: 'A thousand years of history. Not one squash merge.',
      emblem: 'LEGION', finale: 'The repo outlived empires. Tag your releases, people.',
    },
  }),
  base({
    id: 'dc-saturngirl', name: 'Saturn Girl', setting: 'space', settingOpts: { tint: '#d83a5a', planet: '#e8b070' }, layout: 1,
    accent: '#d83a5a', secondary: '#f0d8e0', symbol: 'legion', symbolColor: '#f0c840', sfxFill: '#ffd0dc', sfxRim: '#8a1a3a',
    suit: { head: { hair: 'long', hairColor: '#f0d070', eyes: 'plain' }, torso: '#d83a5a', arms: '#f0e8ec', gloves: '#d83a5a', legs: '#d83a5a', boots: '#f0e8ec', belt: '#f0c840', emblem: 'legion', emblemColor: '#f0c840', handGlow: '#ff9ab8', waist: 0.6, bulk: 0.9 },
    poses: { establish: 'fly', hero: 'cast', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Titan. A telepath who knows what you meant to commit.',
      closeup: 'I read your mind. You meant "git stash", not "git reset --hard".',
      hero: ['Legionnaires —', 'we sync telepathically!'],
      sfx: 'MMMWAAH!', quiet: 'She chairs the review meetings. They are very short.',
      emblem: 'TELEPATH', finale: 'No commit message needed. I already know why.',
    },
  }),
  base({
    id: 'dc-lightninglad', name: 'Lightning Lad', setting: 'storm', settingOpts: { glow: '#f0d040' }, layout: 2,
    accent: '#3a6ad0', secondary: '#f0d040', symbol: 'bolt', symbolColor: '#f0d040', sfxFill: '#fff4a0', sfxRim: '#1a3a7a',
    suit: { head: { hair: 'spiky', hairColor: '#c8402a', eyes: 'plain' }, torso: '#3a6ad0', arms: '#3a6ad0', gloves: '#f0d040', legs: '#3a6ad0', boots: '#f0d040', belt: '#f0d040', emblem: 'bolt', emblemColor: '#f0d040', handGlow: '#fff4a0' },
    poses: { establish: 'cast', hero: 'cast', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Winath. A founding Legionnaire, and the one who always reruns the build.',
      closeup: 'Stand clear. I\'m retriggering the pipeline.',
      hero: ['One bolt —', 'every job, restarted!'],
      sfx: 'KRAKKOW!', quiet: 'Twelve thousand volts. Still waiting on the npm install.',
      emblem: 'CHARGED', finale: 'Lightning never strikes the same commit twice. Bisect does.',
    },
  }),
  base({
    id: 'dc-brainiac5', name: 'Brainiac 5', setting: 'lab', settingOpts: { glow: '#7fe060' }, layout: 3,
    accent: '#5ab840', secondary: '#a050c0', symbol: 'legion', symbolColor: '#f0c840', sfxFill: '#d8ffc8', sfxRim: '#5a2a7a',
    suit: { skin: '#7ac860', head: { mask: '#7ac860', hair: 'short', hairColor: '#f0d070', eyes: 'plain', dots: '#f0f8e0' }, torso: '#a050c0', sides: '#d070d8', arms: '#a050c0', gloves: '#a050c0', legs: '#a050c0', boots: '#d070d8', belt: '#f0c840', emblem: 'legion', emblemColor: '#f0c840', handGlow: '#7fe060' },
    poses: { establish: 'stand', hero: 'hips', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Colu. A twelfth-level intellect, and he still forgets to pull.',
      closeup: 'I computed every possible merge order. Yours is the worst.',
      hero: ['The answer is', 'O(log n). Obviously.'],
      sfx: 'ZZWEEP!', quiet: 'He wrote a bisect in his head. It found the bug before he blinked.',
      emblem: 'BISECTED', finale: 'Genius is just a very fast git log.',
    },
  }),

  // ---------------- Anti-heroes ----------------
  base({
    id: 'dc-catwoman', name: 'Catwoman', settingOpts: { time: 'night' }, layout: 0,
    accent: '#2a2a34', secondary: '#7a5aa8', symbol: 'diamond', symbolColor: '#e8f4ff', sfxRim: '#3a2a5a',
    suit: { head: { type: 'cowl', mask: '#1a1a22', eyes: 'plain', ears: true, goggles: '#c8e050' }, torso: '#1a1a22', arms: '#1a1a22', gloves: '#1a1a22', legs: '#1a1a22', boots: '#1a1a22', tallBoots: true, belt: '#3a3048', prop: 'whip', waist: 0.58, bulk: 0.9 },
    poses: { establish: 'crouch', hero: 'crouch', action: 'leap', quiet: 'crouch', finale: 'hips' },
    lines: {
      caption: 'A penthouse. A safe. A private repository with a public fork.',
      closeup: 'Purr-fect. Somebody committed the .env file.',
      hero: ['Finders keepers.', 'It\'s in the history forever, darling.'],
      sfx: 'SNAPP!', quiet: 'Rotate your keys. Rewriting history won\'t take them back.',
      emblem: 'LEAKED', finale: 'Curiosity killed the cat. A secrets scanner saved her.',
    },
  }),
  base({
    id: 'dc-harley', name: 'Harley Quinn', settingOpts: { time: 'dusk' }, layout: 1,
    accent: '#d8304a', secondary: '#2a2a30', symbol: 'diamond', symbolColor: '#d8304a', sfxFill: '#ffb0c0', sfxRim: '#2a2a30',
    suit: { head: { hair: 'long', hairColor: '#f0e0c0', eyes: 'plain', mask: '#f4f0f0', bandana: INK, mouth: true }, skin: '#f4f0f0', torso: '#d8304a', sides: '#1a1a20', arms: '#d8304a', gloves: '#1a1a20', legs: '#1a1a20', boots: '#d8304a', belt: '#1a1a20', prop: 'staff', waist: 0.6, bulk: 0.92 },
    poses: { establish: 'leap', hero: 'hips', action: 'punch', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Arkham Asylum. A psychiatrist, a mallet, and a very chaotic branch.',
      closeup: 'Hiya, puddin\'! I renamed every branch!',
      hero: ['Now they\'re all called', '"final-final-v2-REAL"!'],
      sfx: 'BONKK!', quiet: 'Her commit messages are all hearts. Every single one.',
      emblem: 'CHAOS', finale: 'Nobody said history had to be linear, sweetie.',
    },
  }),
  base({
    id: 'dc-deathstroke', name: 'Deathstroke', settingOpts: { time: 'night' }, layout: 2,
    accent: '#e07a2a', secondary: '#1a1a20', symbol: 'diamond', symbolColor: '#e07a2a', sfxRim: '#1a1a20',
    suit: { head: { mask: '#1a1a20', half: '#e07a2a', eyes: 'plain' }, torso: '#2a3a6a', sides: '#1a1a20', arms: '#2a3a6a', gloves: '#e07a2a', legs: '#2a3a6a', boots: '#e07a2a', belt: '#1a1a20', prop: 'sword', swordsBack: true, bulk: 1.2 },
    poses: { establish: 'crouch', hero: 'hips', action: 'punch', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'A rooftop. A contract. One target: a function nobody calls.',
      closeup: 'I\'m being paid to delete dead code.',
      hero: ['Ninety percent of my brain.', 'One hundred percent of your diff.'],
      sfx: 'SHHKKT!', quiet: 'He removed four thousand lines. The tests didn\'t notice.',
      emblem: 'TERMINATED', finale: 'Nothing personal. Just git rm.',
    },
  }),
  base({
    id: 'dc-redhood', name: 'Red Hood', settingOpts: GOTHAM, layout: 3,
    accent: '#c02a2a', secondary: '#2a2a30', symbol: 'bat', symbolColor: '#c02a2a', sfxRim: '#2a2a30',
    suit: { head: { mask: '#c02a2a', eyes: 'lens', lens: '#f4f6fa' }, torso: '#2a2a30', arms: '#5a4a3a', gloves: '#1a1a20', legs: '#2a2a34', boots: '#1a1a20', belt: '#5a4a3a', emblem: 'bat', emblemColor: '#c02a2a', prop: 'blasters', bulk: 1.15 },
    poses: { establish: 'crouch', hero: 'hips', action: 'punch', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Crime Alley. A Robin came back from the dead. So did his branch.',
      closeup: 'You deleted me. The reflog didn\'t.',
      hero: ['Different methods.', 'Same codebase.'],
      sfx: 'BLAM BLAM!', quiet: 'git checkout -b jason. Restored from a dangling commit.',
      emblem: 'RESTORED', finale: 'Your rules worked fine. Until somebody force-pushed.',
    },
  }),
  base({
    id: 'dc-constantine', name: 'John Constantine', setting: 'mystic', settingOpts: { glow: '#ff9a40', tint: '#2a1a10' }, layout: 0,
    accent: '#c8a24a', secondary: '#2a1a10', symbol: 'fire', symbolColor: '#ff6a2a', sfxFill: '#ffd8a0', sfxRim: '#5a2a10',
    suit: { head: { hair: 'short', hairColor: '#d8b860', eyes: 'plain' }, torso: '#c8a24a', vest: '#f0ece0', arms: '#c8a24a', gloves: SKIN.light, legs: '#2a2a30', boots: '#1a1a20', belt: '#8a1a1a', handGlow: '#ff9a40' },
    poses: { establish: 'stand', hero: 'stand', action: 'cast', quiet: 'stand', finale: 'stand' },
    lines: {
      caption: 'London. A trench coat, a cigarette, and a cursed legacy codebase.',
      closeup: 'Bloody hell. Who wrote this in 2003?',
      hero: ['Demons, I can handle.', 'This regex? Not a chance.'],
      sfx: 'FWAKOOM!', quiet: 'Every binding circle needs a .gitignore. Ask him how he knows.',
      emblem: 'EXORCISED', finale: 'I don\'t fix code. I make deals with it.',
    },
  }),
  base({
    id: 'dc-swampthing', name: 'Swamp Thing', setting: 'forest', layout: 1,
    accent: '#4a7a3a', secondary: '#c84a3a', symbol: 'gem', symbolColor: '#c84a3a', sfxFill: '#d8f0b0', sfxRim: '#2a4a1a',
    suit: { skin: '#4a7a3a', head: { mask: '#4a7a3a', hair: 'spiky', hairColor: '#2a5a2a', eyes: 'glow', eyeColor: '#ff5a3a', jaw: 1.2 }, torso: '#4a7a3a', arms: '#4a7a3a', gloves: '#3a6a2a', legs: '#4a7a3a', boots: '#3a5a2a', bulk: 1.6, abs: true },
    poses: { establish: 'stand', hero: 'stand', action: 'punch', quiet: 'stand', finale: 'stand' },
    lines: {
      caption: 'The Louisiana bayou. Here, every branch grows on its own.',
      closeup: 'I… am… the Green.',
      hero: ['Every branch', 'is connected to the root.'],
      sfx: 'SKRUNCH!', quiet: 'Branches that never merge just turn back into compost.',
      emblem: 'ROOTED', finale: 'Prune your branches. The swamp does.',
    },
  }),
  base({
    id: 'dc-lobo', name: 'Lobo', setting: 'space', settingOpts: { tint: '#3a3a6a', planet: '#c8302a' }, layout: 2,
    accent: '#c8ccd8', secondary: '#c8302a', symbol: 'skull', symbolColor: '#f0f0f4', sfxFill: '#ff8a6a', sfxRim: '#1a1a20',
    suit: { skin: '#d8dce4', head: { mask: '#d8dce4', hair: 'long', hairColor: '#141418', eyes: 'glow', eyeColor: '#ff3a3a', fangs: true, mouth: false, jaw: 1.2 }, torso: '#1a1a20', arms: '#d8dce4', gloves: '#1a1a20', legs: '#1a1a20', boots: '#1a1a20', belt: '#9a9aa8', emblem: 'skull', emblemColor: '#f0f0f4', bulk: 1.5 },
    poses: { establish: 'stand', hero: 'hips', action: 'punch', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Somewhere in space. The Main Man is on the job. The job is a merge.',
      closeup: 'Bastich didn\'t write a commit message.',
      hero: ['Feetal\'s gizz!', 'Who needs a code review?!'],
      sfx: 'FRAG!', quiet: 'He has never once used --force-with-lease. Only --force.',
      emblem: 'FORCED', finale: 'The Main Man always pushes last. Everyone else is gone.',
    },
  }),
  base({
    id: 'dc-blackadam', name: 'Black Adam', setting: 'canyon', layout: 3,
    accent: '#1a1a20', secondary: '#d4a83a', symbol: 'bolt', symbolColor: '#f0c840', sfxFill: '#ffe070', sfxRim: '#1a1a20',
    suit: { skin: SKIN.tan, head: { hair: 'short', hairColor: '#141010', eyes: 'plain', jaw: 1.15 }, torso: '#1a1a20', arms: '#1a1a20', gloves: '#d4a83a', legs: '#1a1a20', boots: '#d4a83a', belt: '#d4a83a', emblem: 'bolt', emblemColor: '#d4a83a', bulk: 1.35 },
    poses: { establish: 'fly', hero: 'hips', action: 'punch', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Kahndaq. Five thousand years of history, and he rules every line of it.',
      closeup: 'This repository is mine by right.',
      hero: ['Kneel', 'before your maintainer.'],
      sfx: 'KRA-THOOM!', quiet: 'He protects his branch. Nobody else may push. Ever.',
      emblem: 'PROTECTED', finale: 'I am no hero. I am branch protection.',
    },
  }),
  base({
    id: 'dc-poisonivy', name: 'Poison Ivy', setting: 'forest', layout: 0,
    accent: '#3a8a3a', secondary: '#c83a3a', symbol: 'gem', symbolColor: '#e0404a', sfxFill: '#d8ffc0', sfxRim: '#1a4a1a',
    suit: { skin: '#c8e0b0', head: { mask: '#c8e0b0', hair: 'long', hairColor: '#c8402a', eyes: 'plain', mouth: true }, torso: '#3a8a3a', arms: '#c8e0b0', gloves: '#3a8a3a', legs: '#2a6a2a', boots: '#3a8a3a', tallBoots: true, belt: '#2a6a2a', handGlow: '#7aff6a', waist: 0.58, bulk: 0.9 },
    poses: { establish: 'cast', hero: 'hips', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Robinson Park. The vines have taken the server room.',
      closeup: 'You prune my branches? I prune yours.',
      hero: ['Grow, my darlings.', 'Every branch — forever.'],
      sfx: 'SHHRRUSHH!', quiet: 'Four hundred stale branches. She loves every one of them.',
      emblem: 'OVERGROWN', finale: 'Nature has no main. Only branches.',
    },
  }),
  base({
    id: 'dc-peacemaker', name: 'Peacemaker', settingOpts: { time: 'day' }, layout: 1,
    accent: '#e8e8f0', secondary: '#3a6ad0', symbol: 'dove', symbolColor: '#ffffff', sfxRim: '#3a6ad0',
    suit: { head: { mask: SKIN.light, eyes: 'plain', helm: '#d8dce4', mouth: true }, torso: '#3a6ad0', arms: '#e8e8f0', gloves: '#e8e8f0', legs: '#e8e8f0', boots: '#3a6ad0', belt: '#c8302a', emblem: 'dove', emblemColor: '#ffffff', prop: 'gun', bulk: 1.2 },
    poses: { establish: 'stand', hero: 'hips', action: 'punch', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Evergreen. He loves peace so much he\'ll force-push anyone to get it.',
      closeup: 'I cherish peace with all my heart.',
      hero: ['I don\'t care how many', 'commits I have to revert!'],
      sfx: 'BLAMMO!', quiet: 'His helmet is chrome. His history is not.',
      emblem: 'PEACE', finale: 'A clean history at any cost. Any cost.',
    },
  }),

  // ---------------- Villains ----------------
  base({
    id: 'dc-joker', name: 'The Joker', settingOpts: { time: 'dusk' }, layout: 2,
    accent: '#7a3ab0', secondary: '#5ab84a', symbol: 'ha', symbolColor: '#5ab84a', sfxFill: '#c8ff9a', sfxRim: '#4a1a7a',
    suit: { skin: '#f4f4f0', head: { mask: '#f4f4f0', hair: 'spiky', hairColor: '#4aa83a', eyes: 'plain', fangs: true, mouth: false }, torso: '#7a3ab0', vest: '#e08a2a', arms: '#7a3ab0', gloves: '#7a3ab0', legs: '#7a3ab0', boots: '#2a2a30', waist: 0.62 },
    poses: { establish: 'hips', hero: 'hips', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Ace Chemicals. Somebody merged a commit called "lol".',
      closeup: 'Why so serious? It\'s only production.',
      hero: ['All it takes is one bad push', 'to drive a repo mad!'],
      sfx: 'HAHAHAHA!', quiet: 'He rebased main onto a joke branch. It passed CI.',
      emblem: 'WHY SO SERIOUS', finale: 'If you\'re going to force-push, have a laugh doing it.',
    },
  }),
  base({
    id: 'dc-luthor', name: 'Lex Luthor', setting: 'lab', settingOpts: { glow: '#5aff7a' }, layout: 3,
    accent: '#3aa050', secondary: '#7a4ab0', symbol: 'lex', symbolColor: '#5aff7a', sfxFill: '#c8ffd0', sfxRim: '#3a1a6a',
    suit: { head: { hair: 'none', eyes: 'plain', jaw: 1.1 }, torso: '#3aa050', sides: '#7a4ab0', arms: '#3aa050', gloves: '#7a4ab0', legs: '#7a4ab0', boots: '#3aa050', belt: '#2a2a30', emblem: 'lex', emblemColor: '#5aff7a', handGlow: '#5aff7a', bulk: 1.35 },
    poses: { establish: 'stand', hero: 'hips', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'LexCorp Tower. A man who believes every repo should be private. His.',
      closeup: 'Brains over brawn. Static types over vibes.',
      hero: ['I bought the remote.', 'Your fork is now proprietary.'],
      sfx: 'ZZRAKKOW!', quiet: 'He lost to an alien. He has never lost a license dispute.',
      emblem: 'PROPRIETARY', finale: 'Kryptonite for him. A restrictive license for you.',
    },
  }),
  base({
    id: 'dc-darkseid', name: 'Darkseid', setting: 'hell', layout: 0,
    accent: '#c83a2a', secondary: '#3a4a6a', symbol: 'omega', symbolColor: '#ff4a3a', sfxFill: '#ffb090', sfxRim: '#1a1a24',
    suit: { skin: '#6a6a72', head: { mask: '#6a6a72', eyes: 'glow', eyeColor: '#ff3a2a', jaw: 1.35, helm: '#3a4a6a', mouth: true }, torso: '#3a4a6a', arms: '#6a6a72', gloves: '#3a4a6a', legs: '#3a4a6a', boots: '#3a4a6a', belt: '#2a2a34', emblem: 'omega', emblemColor: '#ff4a3a', bulk: 1.7 },
    poses: { establish: 'stand', hero: 'hips', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Apokolips. A world where every developer works on one branch: his.',
      closeup: 'I am the Anti-Life Equation. Also, the only approver.',
      hero: ['There is no free will.', 'There is only main.'],
      sfx: 'ZZZAAARRK!', quiet: 'Omega beams. They bend around every guard rail.',
      emblem: 'OMEGA', finale: 'Kneel. And squash.',
    },
  }),
  base({
    id: 'dc-sinestro', name: 'Sinestro', setting: 'space', settingOpts: { tint: '#c8a020', planet: '#9a3ab0' }, layout: 1,
    accent: '#e8c030', secondary: '#1a1a20', symbol: 'sinestro', symbolColor: '#ffe040', sfxFill: '#fff4a0', sfxRim: '#5a1a5a',
    suit: { skin: '#b04aa0', head: { mask: '#b04aa0', hair: 'short', hairColor: '#141010', eyes: 'plain', jaw: 1.1 }, torso: '#1a1a20', sides: '#e8c030', arms: '#1a1a20', gloves: '#e8c030', legs: '#1a1a20', boots: '#1a1a20', emblem: 'sinestro', emblemColor: '#ffe040', handGlow: '#ffe040', aura: ['#ffe040', '#fff6c0'] },
    poses: { establish: 'fly', hero: 'hips', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Korugar. Order through fear. And through mandatory status checks.',
      closeup: 'Fear is the only thing that makes them write tests.',
      hero: ['Twelve required checks.', 'Three approvals. Fear me.'],
      sfx: 'VRRRAAAM!', quiet: 'He turned on every lint rule at once. The repo has never been so quiet.',
      emblem: 'FEAR', finale: 'Willpower fades. A failing pipeline is forever.',
    },
  }),
  base({
    id: 'dc-reverseflash', name: 'Reverse-Flash', settingOpts: { time: 'dusk' }, layout: 2,
    accent: '#e0c030', secondary: '#c82a2a', symbol: 'rflash', symbolColor: '#c82a2a', sfxFill: '#ffb0a0', sfxRim: '#1a1a20',
    suit: { head: { mask: '#e0c030', eyes: 'glow', eyeColor: '#ff3a2a', type: 'cowl', wings: '#c82a2a' }, torso: '#e0c030', arms: '#e0c030', gloves: '#e0c030', legs: '#e0c030', boots: '#c82a2a', belt: '#c82a2a', emblem: 'rflash', emblemColor: '#c82a2a', waist: 0.66 },
    poses: { establish: 'leap', hero: 'hips', action: 'leap', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'The 25th century, on the way back. He rewrites the past for fun.',
      closeup: 'I was here first. Check the author date.',
      hero: ['I amended your commit', 'before you made it.'],
      sfx: 'ZRRAAWM!', quiet: 'He sets GIT_COMMITTER_DATE to the year 2491. Every time.',
      emblem: 'AMENDED', finale: 'The Speed Force is just history rewriting, very fast.',
    },
  }),
  base({
    id: 'dc-bane', name: 'Bane', settingOpts: GOTHAM, layout: 3,
    accent: '#3aa050', secondary: '#1a1a20', symbol: 'skull', symbolColor: '#dfe4ec', sfxFill: '#c8ffd0', sfxRim: '#1a1a20',
    suit: { head: { mask: '#1a1a20', eyes: 'white', mouth: false }, torso: '#2a2a30', arms: SKIN.tan, gloves: '#1a1a20', legs: '#2a2a30', boots: '#1a1a20', belt: '#1a1a20', bulk: 1.85, abs: true, armStripe: '#5aff7a' },
    poses: { establish: 'stand', hero: 'hips', action: 'punch', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Peña Duro. He studied the codebase for years before he touched it.',
      closeup: 'You merely adopted the legacy code.',
      hero: ['I was born in it.', 'Moulded by it.'],
      sfx: 'KRAKKK!', quiet: 'He read every line before he broke the build. Methodically.',
      emblem: 'BROKEN', finale: 'Peace has cost you your pipeline. Victory has defeated your tests.',
    },
  }),
  base({
    id: 'dc-twoface', name: 'Two-Face', settingOpts: GOTHAM, layout: 0,
    accent: '#d8d8e0', secondary: '#1a1a20', symbol: 'ring', symbolColor: '#d8d8e0', sfxRim: '#5a2a2a',
    suit: { head: { hair: 'short', hairColor: '#2a2018', eyes: 'plain', half: '#8a4a5a' }, torso: '#e8e8ee', sides: '#1a1a20', arms: '#e8e8ee', gloves: SKIN.light, legs: '#1a1a20', boots: '#1a1a20', bulk: 1.1 },
    poses: { establish: 'stand', hero: 'hips', action: 'punch', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Gotham. A district attorney who could never decide between merge and rebase.',
      closeup: 'Heads, we merge. Tails, we rebase.',
      hero: ['The coin decides.', 'Not you. Not me.'],
      sfx: 'TINNG!', quiet: 'He keeps two branches of everything. They never agree.',
      emblem: 'HEADS', finale: 'You either merge a hero, or rebase long enough to become the villain.',
    },
  }),
  base({
    id: 'dc-riddler', name: 'The Riddler', settingOpts: { time: 'night' }, layout: 1,
    accent: '#4ab04a', secondary: '#7a4ab0', symbol: 'question', symbolColor: '#5ad05a', sfxFill: '#c8ffb0', sfxRim: '#3a1a6a',
    suit: { head: { hair: 'short', hairColor: '#8a4a2a', eyes: 'plain', bandana: '#7a4ab0', hat: 'bowler', hatColor: '#3a8a3a', hatBand: '#7a4ab0' }, torso: '#4ab04a', arms: '#4ab04a', gloves: '#7a4ab0', legs: '#4ab04a', boots: '#2a2a30', belt: '#7a4ab0', prop: 'qcane', waist: 0.62 },
    poses: { establish: 'stand', hero: 'hips', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Gotham. A puzzle left on every branch.',
      closeup: 'Riddle me this: when is a commit not a commit?',
      hero: ['When it\'s dangling!', 'HA! Too easy!'],
      sfx: 'ZINNG!', quiet: 'His commit messages are riddles. His variable names are worse.',
      emblem: '???', finale: 'What has a HEAD and a tail but no body? Your repository.',
    },
  }),
  base({
    id: 'dc-penguin', name: 'The Penguin', settingOpts: { time: 'night' }, layout: 2,
    accent: '#2a2a34', secondary: '#7a3a8a', symbol: 'diamond', symbolColor: '#cfe8ff', sfxRim: '#2a2a34',
    suit: { head: { hair: 'none', eyes: 'plain', hat: 'top', hatColor: '#1a1a20', hatBand: '#5a2a6a', jaw: 1.2 }, torso: '#1a1a22', vest: '#f4f4f8', arms: '#1a1a22', gloves: '#e8e8f0', legs: '#1a1a22', boots: '#1a1a20', prop: 'umbrella', bulk: 1.6, waist: 1.1 },
    poses: { establish: 'stand', hero: 'hips', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'The Iceberg Lounge. All the best leaked credentials are sold here.',
      closeup: 'Wak wak wak. Your token, please.',
      hero: ['Every umbrella', 'hides a merge tool.'],
      sfx: 'FWOOMP!', quiet: 'He runs the black market for unreviewed pull requests.',
      emblem: 'FROZEN', finale: 'A gentleman never commits his own secrets. He sells yours.',
    },
  }),
  base({
    id: 'dc-scarecrow', name: 'Scarecrow', setting: 'forest', layout: 3,
    accent: '#b89a5a', secondary: '#3a6a2a', symbol: 'skull', symbolColor: '#c8a868', sfxFill: '#c8ffb0', sfxRim: '#2a2010',
    suit: { head: { mask: '#c8a868', eyes: 'glow', eyeColor: '#7aff6a', hat: 'bowler', hatColor: '#4a3a2a', fangs: true, mouth: false }, torso: '#6a5a3a', arms: '#6a5a3a', gloves: '#4a3a2a', legs: '#5a4a30', boots: '#3a2a1a', belt: '#8a6a3a', bulk: 0.85, waist: 0.6 },
    poses: { establish: 'stand', hero: 'cast', action: 'cast', quiet: 'stand', finale: 'stand' },
    lines: {
      caption: 'A cornfield outside Gotham. The fear toxin is a single word: "conflict".',
      closeup: 'What are you afraid of? Let\'s find out.',
      hero: ['Your worst fear:', 'a rebase with 300 commits.'],
      sfx: 'HISSSSS!', quiet: 'Under the gas they all see the same thing. A detached HEAD.',
      emblem: 'FEAR', finale: 'Fear is just a merge you haven\'t tried yet.',
    },
  }),
  base({
    id: 'dc-freeze', name: 'Mr. Freeze', setting: 'ice', layout: 0,
    accent: '#7ac8e8', secondary: '#c8d4e0', symbol: 'gem', symbolColor: '#bfe8ff', sfxFill: '#e8f8ff', sfxRim: '#1a4a6a',
    suit: { skin: '#d8e8f0', head: { type: 'bowl', glass: '#cfefff', smoke: '#7ac8e8' }, torso: '#c8d4e0', sides: '#7ac8e8', arms: '#c8d4e0', gloves: '#5a8ab0', legs: '#c8d4e0', boots: '#5a8ab0', belt: '#5a8ab0', emblem: 'gem', emblemColor: '#7ac8e8', prop: 'blasters', bulk: 1.35 },
    poses: { establish: 'stand', hero: 'hips', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'GothCorp\'s cryo lab. A man who froze his whole release branch.',
      closeup: 'Code freeze. Effective immediately. Forever.',
      hero: ['Chill.', 'Nothing merges now.'],
      sfx: 'KSSSHHH!', quiet: 'The release has been frozen for nineteen months. He calls it stability.',
      emblem: 'CODE FREEZE', finale: 'Everything thaws eventually. Except a frozen tag.',
    },
  }),
  base({
    id: 'dc-brainiac', name: 'Brainiac', setting: 'space', settingOpts: { tint: '#2a8a4a', planet: '#c84aa0' }, layout: 1,
    accent: '#4ab860', secondary: '#c84aa0', symbol: 'gem', symbolColor: '#8aff9a', sfxFill: '#c8ffd0', sfxRim: '#4a1a4a',
    suit: { skin: '#5ab86a', head: { mask: '#5ab86a', hair: 'none', eyes: 'white', dots: '#c84aa0' }, torso: '#c84aa0', sides: '#4ab860', arms: '#5ab86a', gloves: '#c84aa0', legs: '#c84aa0', boots: '#4ab860', belt: '#4ab860', emblem: 'gem', emblemColor: '#8aff9a', handGlow: '#8aff9a', bulk: 1.15 },
    poses: { establish: 'stand', hero: 'hips', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'The skull ship. A collector of every repository ever written.',
      closeup: 'Your codebase is… quaint. I will clone it.',
      hero: ['I keep every city', 'in a bottle. And a mirror.'],
      sfx: 'VZZZT!', quiet: 'His collection: ten billion mirrors. Zero pull requests opened.',
      emblem: 'CLONED', finale: 'Knowledge is to be collected. Never contributed back.',
    },
  }),
  base({
    id: 'dc-doomsday', name: 'Doomsday', setting: 'canyon', layout: 2,
    accent: '#a8a498', secondary: '#3a5a2a', symbol: 'skull', symbolColor: '#e8e0d0', sfxFill: '#ffe0b0', sfxRim: '#2a2a20',
    suit: { skin: '#8a8a80', head: { mask: '#8a8a80', hair: 'spiky', hairColor: '#e8e0d0', eyes: 'glow', eyeColor: '#ff5a3a', fangs: true, mouth: false, jaw: 1.3 }, torso: '#8a8a80', arms: '#8a8a80', gloves: '#8a8a80', legs: '#3a5a2a', boots: '#8a8a80', shoulderPads: '#e8e0d0', bulk: 1.9, abs: true },
    poses: { establish: 'leap', hero: 'stand', action: 'punch', quiet: 'stand', finale: 'stand' },
    lines: {
      caption: 'It came out of the ground and started deleting branches.',
      closeup: 'RRRAAAGH.',
      hero: ['DESTROY.', 'ALL. BRANCHES.'],
      sfx: 'KRA-THOOOM!', quiet: 'It adapts to every fix. Every hotfix makes it stronger.',
      emblem: 'DOOMSDAY', finale: 'The day the build died. Rest in peace, main.',
    },
  }),
  base({
    id: 'dc-blackmanta', name: 'Black Manta', setting: 'sea', layout: 3,
    accent: '#c02a2a', secondary: '#1a1e26', symbol: 'diamond', symbolColor: '#ff3a3a', sfxFill: '#ffb0a0', sfxRim: '#1a1e26',
    suit: { head: { mask: '#1a1e26', eyes: 'lens-big', lens: '#ff3a3a', mouth: false }, headScale: 1.45, torso: '#1a1e26', arms: '#1a1e26', gloves: '#2a3040', legs: '#1a1e26', boots: '#2a3040', belt: '#c02a2a', emblem: 'diamond', emblemColor: '#c02a2a', handGlow: '#ff4a4a', bulk: 1.15 },
    poses: { establish: 'leap', hero: 'hips', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'The deep. A grudge older than this repository.',
      closeup: 'I have been watching your history for a long time.',
      hero: ['Every commit you made,', 'I made one to revert it.'],
      sfx: 'ZZRAAAK!', quiet: 'A revert of a revert of a revert. Nobody remembers the original change.',
      emblem: 'REVERTED', finale: 'The ocean is deep. So is my grudge. So is this blame.',
    },
  }),
  base({
    id: 'dc-cheetah', name: 'Cheetah', setting: 'canyon', layout: 0,
    accent: '#d8a03a', secondary: '#3a2a1a', symbol: 'diamond', symbolColor: '#3a2a1a', sfxFill: '#ffe0a0', sfxRim: '#3a2a1a',
    suit: { skin: '#d8a03a', head: { mask: '#d8a03a', hair: 'long', hairColor: '#e8c070', eyes: 'glow', eyeColor: '#a0ff6a', ears: true, fangs: true, mouth: false }, torso: '#d8a03a', arms: '#d8a03a', gloves: '#d8a03a', legs: '#d8a03a', boots: '#d8a03a', spots: '#3a2a1a', prop: 'claws', tail: '#d8a03a', waist: 0.58, bulk: 0.95 },
    poses: { establish: 'leap', hero: 'crouch', action: 'leap', quiet: 'crouch', finale: 'hips' },
    lines: {
      caption: 'The jungle. She hunts the fastest moving branch in the repo.',
      closeup: 'You can\'t outrun me. Not even with --no-verify.',
      hero: ['Speed is nothing', 'without a stable base.'],
      sfx: 'SKRAAATCH!', quiet: 'She rebases onto main every hour. Out of pure jealousy.',
      emblem: 'PREDATOR', finale: 'Run fast, push faster. I\'ll still catch your typo.',
    },
  }),
  base({
    id: 'dc-rasalghul', name: "Ra's al Ghul", setting: 'temple', layout: 1,
    accent: '#3a8a5a', secondary: '#c8a040', symbol: 'gem', symbolColor: '#7aff9a', sfxFill: '#c8ffd8', sfxRim: '#1a3a24',
    suit: { head: { hair: 'short', hairColor: '#c8c8c8', eyes: 'plain', jaw: 1.05 }, torso: '#2a6a4a', vest: '#c8a040', arms: '#2a6a4a', gloves: '#1a1a20', legs: '#1a3a2a', boots: '#1a1a20', belt: '#c8a040', cape: '#1a3a2a', prop: 'sword', bulk: 1.05 },
    poses: { establish: 'stand', hero: 'hips', action: 'punch', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Nanda Parbat. A man who has lived six hundred years. So has this legacy branch.',
      closeup: 'I have survived every rewrite of this history.',
      hero: ['The Lazarus Pit', 'restores any deleted branch.'],
      sfx: 'SHHHING!', quiet: 'It\'s just git reflog. He insists it is mystical.',
      emblem: 'IMMORTAL', finale: 'The League does not delete. The League waits for gc.',
    },
  }),
];

module.exports = { DC_HEROES };
