// Every character's page: suit, setting, poses and script. Ids match the theme ids in
// src/renderer/js/00-hero-themes.js, which is how the app finds a page for a theme.
//
// The script is original and about git — these are pages *in the style of* the books, not
// copies of any of them.
//
// Suit keys (see figure.js): torso/arms/legs/gloves/boots/belt colours; lower/sides/vest
// for two-tone suits; cape, emblem, prop, bulk, handGlow, aura, wings, tentacles, tail, board.
// head: mask/type ('cowl' shows the lower face, 'skull', 'bowl'), eyes ('lens', 'lens-big',
// 'slit', 'visor', 'plain', 'white'), and hair/hood/horns/ears/crown/… on top.
'use strict';

const SKIN = { light: '#f0c29a', tan: '#d89a6a', brown: '#9a6440', deep: '#6a4028' };
const INK = '#17120f';

// Defaults shared by every entry; each hero overrides what it needs.
const base = (o) => Object.assign({
  setting: 'city', settingOpts: {}, facing: 1,
  accent: '#d8282e', secondary: '#2a5ab8', bg: '#101020',
}, o, {
  poses: Object.assign({ establish: 'stand', hero: 'stand', action: 'punch', quiet: 'stand', finale: 'hips' }, o.poses),
  suit: Object.assign({ skin: SKIN.light }, o.suit),
});

const spiderSuit = (red, blue) => ({
  head: { mask: red, eyes: 'lens', web: true }, torso: red, sides: blue, arms: red, legs: blue, boots: red, gloves: red,
  web: true, emblem: 'spider', emblemColor: INK, waist: 0.66,
});

const HEROES = [
  // ---------------- Heroes ----------------
  base({
    id: 'hero-spider', name: 'Spider-Man', settingOpts: { time: 'day' }, layout: 0,
    accent: '#d8282e', secondary: '#2a5ab8', symbol: 'spider', symbolColor: INK,
    suit: spiderSuit('#d8282e', '#2a5ab8'),
    poses: { establish: 'crouch', hero: 'crouch', action: 'swing', quiet: 'crouch', finale: 'stand' },
    lines: {
      caption: 'Midtown. Forty stories up. One unpushed commit.',
      closeup: "Okay. Deep breath. It's just a rebase.",
      hero: ['Twelve conflicts. Twelve!', 'Who edits the same line in twelve files?'],
      sfx: 'THWIP!', quiet: 'Two days of merging. Nobody said heroics would be this… textual.',
      emblem: 'RESOLVED', finale: 'With great power comes great responsibility. Pull before you push.',
    },
  }),
  base({
    id: 'hero-spider-rev', name: 'Spider-Man Reversed', settingOpts: { time: 'dusk' }, layout: 2,
    accent: '#2a5ab8', secondary: '#d8282e', symbol: 'spider', symbolColor: INK,
    suit: spiderSuit('#2a5ab8', '#d8282e'),
    poses: { establish: 'swing', hero: 'crouch', action: 'leap', finale: 'stand' },
    lines: {
      caption: 'Same city. Same suit. Colours checked out from the other branch.',
      closeup: 'Did I just… swap ours and theirs?',
      hero: ['Nope. Totally meant to.', 'This is my reverted look.'],
      sfx: 'THWIP!', quiet: 'git revert: for when the suit looked better yesterday.',
      emblem: 'REVERTED', finale: 'Every commit can be undone. Most suits can too.',
    },
  }),
  base({
    id: 'hero-ironman', name: 'Iron Man', settingOpts: { time: 'dusk' }, layout: 1,
    accent: '#c8302a', secondary: '#e0b040', symbol: 'arc', symbolColor: '#dffaff', sfxFill: '#bff4ff', sfxRim: '#c8302a',
    suit: { head: { mask: '#c8302a', faceplate: '#e8b840', eyeColor: '#dff8ff' }, torso: '#c8302a', sides: '#e0b040', arms: '#c8302a', legs: '#c8302a', gloves: '#c8302a', boots: '#c8302a', legStripe: '#e0b040', emblem: 'arc', handGlow: '#9fe8ff', bulk: 1.1 },
    poses: { establish: 'fly', hero: 'stand', action: 'cast', quiet: 'stand', finale: 'hips' },
    lines: {
      caption: 'Stark Tower. A continuous-integration pipeline in a flying suit.',
      closeup: 'JARVIS, squash the last forty commits. All of them.',
      hero: ['Genius. Billionaire.', 'Writes his own git hooks.'],
      sfx: 'FSSHOOOM!', quiet: 'Mark 85. The history says the first 84 were "wip".',
      emblem: 'DEPLOYED', finale: 'I am Iron Man. And I sign my commits.',
    },
  }),
  base({
    id: 'hero-cap', name: 'Captain America', settingOpts: { time: 'day' }, layout: 3,
    accent: '#2f5aa8', secondary: '#c8302a', symbol: 'star', symbolColor: '#ffffff',
    suit: { head: { type: 'cowl', mask: '#2f5aa8', eyes: 'plain', letter: 'A', wings: '#ffffff' }, torso: '#2f5aa8', lower: '#c8302a', arms: '#2f5aa8', gloves: '#c8302a', legs: '#2f5aa8', boots: '#c8302a', belt: '#8a6a4a', emblem: 'star', prop: 'shield', bulk: 1.15 },
    poses: { establish: 'stand', hero: 'stand', action: 'punch', finale: 'hips' },
    lines: {
      caption: 'Brooklyn. A man out of time, and out of date with origin.',
      closeup: 'I can do this all day. The merge, I mean.',
      hero: ['Avengers — pull!', 'Then we push. Together.'],
      sfx: 'KLANGG!', quiet: 'Seventy years on ice. Still fewer conflicts than this branch.',
      emblem: 'ASSEMBLE', finale: 'I don\'t like force-pushers. Doesn\'t matter where they\'re from.',
    },
  }),
  base({
    id: 'hero-thor', name: 'Thor', setting: 'asgard', layout: 0,
    accent: '#c8302a', secondary: '#4a7ad0', symbol: 'bolt', symbolColor: '#fff4a0', sfxFill: '#fff4a0',
    suit: { head: { hair: 'long', hairColor: '#e8c050', eyes: 'plain', brow: '#a07a20' }, torso: '#3a4250', arms: SKIN.light, legs: '#2a2e38', boots: '#5a4a3a', gloves: '#3a4250', longGloves: false, belt: '#a08040', cape: '#c8302a', emblem: 'ring', emblemColor: '#c8d0dc', prop: 'hammer', bulk: 1.25, abs: true },
    poses: { establish: 'fly', hero: 'stand', action: 'punch', finale: 'hips' },
    lines: {
      caption: 'Asgard. Where every branch leads, eventually, to main.',
      closeup: 'Who dares force-push to the realm eternal?',
      hero: ['I am worthy of this merge!', 'Bring me the conflicted files!'],
      sfx: 'KRAKOOM!', quiet: 'Even gods must write a commit message.',
      emblem: 'WORTHY', finale: 'Another! …Another pull request, I mean.',
    },
  }),
  base({
    id: 'hero-hulk', name: 'Hulk', setting: 'canyon', layout: 2,
    accent: '#5aa040', secondary: '#7a4ab0', symbol: 'fire', symbolColor: '#7fd05a', sfxFill: '#9fe070', sfxRim: '#5a2a90',
    suit: { skin: '#6ab04a', head: { hair: 'short', hairColor: '#1e2a1a', eyes: 'plain', jaw: 1.25 }, torso: '#6ab04a', arms: '#6ab04a', legs: '#6a3aa0', boots: '#6ab04a', gloves: '#6ab04a', bulk: 1.75, abs: true, waist: 0.8 },
    poses: { establish: 'leap', hero: 'stand', action: 'punch', finale: 'hips' },
    lines: {
      caption: 'The desert. Where Banner went to cool off after a code review.',
      closeup: 'Hulk read the diff.',
      hero: ['HULK SMASH MERGE CONFLICT!'],
      sfx: 'SMAAASH!', quiet: 'Banner\'s advice: small commits. Hulk\'s advice: SMALLER.',
      emblem: 'SMASH', finale: 'Hulk not angry. Hulk just rebase.',
    },
  }),
  base({
    id: 'hero-widow', name: 'Black Widow', settingOpts: { time: 'night' }, layout: 1,
    accent: '#c0343c', secondary: '#2a2a34', symbol: 'hourglass', symbolColor: '#e0404a',
    suit: { head: { hair: 'long', hairColor: '#c0402a', eyes: 'plain' }, torso: '#24242c', arms: '#24242c', legs: '#24242c', boots: '#1a1a20', gloves: '#1a1a20', belt: '#c0343c', emblem: 'hourglass', emblemColor: '#e0404a', prop: 'gun', waist: 0.6, bulk: 0.92 },
    poses: { establish: 'crouch', hero: 'stand', action: 'leap', quiet: 'crouch', finale: 'hips' },
    lines: {
      caption: 'Budapest, again. Some histories never get garbage-collected.',
      closeup: 'I\'ve got red in my ledger. And in my diff.',
      hero: ['Stash it. We move quietly.'],
      sfx: 'WHAKK!', quiet: 'A clean working tree is the best alibi.',
      emblem: 'STASHED', finale: 'I don\'t leave dangling commits.',
    },
  }),
  base({
    id: 'hero-hawkeye', name: 'Hawkeye', settingOpts: { time: 'dusk' }, layout: 3,
    accent: '#7a48b0', secondary: '#d0a24a', symbol: 'ring', symbolColor: '#ffffff',
    suit: { head: { hair: 'short', hairColor: '#c0a060', eyes: 'plain', bandana: '#6a3a9a' }, torso: '#3a2a4a', vest: '#7a48b0', arms: SKIN.light, gloves: '#3a2a4a', legs: '#2a2034', boots: '#3a2a4a', belt: '#d0a24a', prop: 'bow' },
    poses: { establish: 'stand', hero: 'stand', action: 'cast', finale: 'hips' },
    lines: {
      caption: 'A rooftop. One arrow. One exact commit to cherry-pick.',
      closeup: 'I never miss. `git cherry-pick 4f2a9c1`.',
      hero: ['Trick arrow: bisect.', 'Finds the bug in seven shots.'],
      sfx: 'TWANGG!', quiet: 'The guy with the bow keeps the cleanest log.',
      emblem: 'BULLSEYE', finale: 'You know what they say. Aim small, commit small.',
    },
  }),
  base({
    id: 'hero-panther', name: 'Black Panther', setting: 'wakanda', layout: 0,
    accent: '#7a52d8', secondary: '#c3c6d4', symbol: 'diamond', symbolColor: '#b99cff', sfxFill: '#d8c8ff', sfxRim: '#3a2a70',
    suit: { head: { mask: '#1a1820', eyes: 'lens', lens: '#e0dcf0', ears: true }, torso: '#1a1820', arms: '#1a1820', legs: '#1a1820', gloves: '#1a1820', boots: '#1a1820', belt: '#c3c6d4', emblem: 'diamond', emblemColor: '#b99cff', handGlow: '#a080ff', waist: 0.64 },
    poses: { establish: 'crouch', hero: 'stand', action: 'leap', quiet: 'crouch', finale: 'hips' },
    lines: {
      caption: 'Wakanda. The only repository never once leaked to the public.',
      closeup: 'Wakanda keeps its secrets in .gitignore.',
      hero: ['The kinetic energy of every push —', 'stored, and returned.'],
      sfx: 'SHRAKK!', quiet: 'In times of crisis, the wise build bridges. And tags.',
      emblem: 'FOREVER', finale: 'Wakanda protected. Branch protected.',
    },
  }),
  base({
    id: 'hero-marvel', name: 'Captain Marvel', setting: 'space', settingOpts: { tint: '#c43a48', planet: '#4a7ad8' }, layout: 1,
    accent: '#c43a48', secondary: '#2a4a9a', symbol: 'star', symbolColor: '#f0cc60', sfxFill: '#fff0a0',
    suit: { head: { hair: 'long', hairColor: '#e8c060', eyes: 'plain' }, torso: '#2a4a9a', sides: '#c43a48', arms: '#2a4a9a', gloves: '#c43a48', legs: '#2a4a9a', boots: '#c43a48', legStripe: '#c43a48', belt: '#e2bd4c', emblem: 'star', emblemColor: '#f0cc60', handGlow: '#ffe07a', aura: ['#ffd98a', '#fff4c8'], waist: 0.62 },
    poses: { establish: 'fly', hero: 'fly', action: 'cast', finale: 'hips' },
    lines: {
      caption: 'Low orbit. Somewhere below, a CI pipeline has turned red.',
      closeup: 'Higher. Further. Faster. Greener builds.',
      hero: ['I\'ve got nothing to prove —', 'except these tests pass.'],
      sfx: 'FWOOOSH!', quiet: 'Binary form is just another branch.',
      emblem: 'BINARY', finale: 'Stay green, Earth.',
    },
  }),
  base({
    id: 'hero-wanda', name: 'Scarlet Witch', setting: 'mystic', settingOpts: { glow: '#ff4f7a', tint: '#4a0a2a' }, layout: 2,
    accent: '#c43250', secondary: '#6a1a3a', symbol: 'gem', symbolColor: '#ff5a86', sfxFill: '#ffb0c8', sfxRim: '#8a1a3a',
    suit: { head: { hair: 'long', hairColor: '#8a2a2a', eyes: 'plain', tiara: '#c43250' }, torso: '#9a1a36', arms: '#9a1a36', gloves: '#6a1026', legs: '#3a0a18', boots: '#6a1026', cape: '#c43250', handGlow: '#ff4f7a', waist: 0.6, bulk: 0.9 },
    poses: { establish: 'cast', hero: 'cast', action: 'cast', finale: 'stand' },
    lines: {
      caption: 'Westview. Where the history is… whatever she says it is.',
      closeup: 'No more conflicts.',
      hero: ['I rewrote the whole history.', 'Nobody noticed.'],
      sfx: 'HWAAAM!', quiet: 'Chaos magic is just an interactive rebase with feelings.',
      emblem: 'REWRITTEN', finale: 'What is a branch, if not grief persevering?',
    },
  }),
  base({
    id: 'hero-antman', name: 'Ant-Man', settingOpts: { time: 'day' }, layout: 3,
    accent: '#c8302a', secondary: '#3a3a44', symbol: 'ring', symbolColor: '#c8302a',
    suit: { head: { mask: '#c8302a', eyes: 'lens', lens: '#2a2a30', antenna: '#9aa4b0' }, torso: '#c8302a', sides: '#2a2a30', arms: '#c8302a', gloves: '#2a2a30', legs: '#2a2a30', boots: '#c8302a', belt: '#9aa4b0', emblem: 'ring', emblemColor: '#2a2a30' },
    poses: { establish: 'leap', hero: 'stand', action: 'punch', finale: 'hips' },
    lines: {
      caption: 'San Francisco. The smallest commit in history is about to matter.',
      closeup: 'One line. One tiny, perfect line.',
      hero: ['Shrink the diff!', 'Now it\'s reviewable!'],
      sfx: 'PWOMP!', quiet: 'In the quantum realm, every commit is both merged and not.',
      emblem: 'ATOMIC', finale: 'Small commits, big heroes.',
    },
  }),
  base({
    id: 'hero-wasp', name: 'The Wasp', settingOpts: { time: 'day' }, layout: 1,
    accent: '#d9ad3c', secondary: '#2a2a30', symbol: 'wasp', symbolColor: '#f0c040',
    suit: { head: { hair: 'short', hairColor: '#2a1a14', eyes: 'lens', mask: '#d9ad3c', lens: '#c8302a' }, torso: '#d9ad3c', sides: '#2a2a30', arms: '#2a2a30', gloves: '#d9ad3c', legs: '#2a2a30', boots: '#d9ad3c', wings: 'insect', wingColor: '#ffe9a8', emblem: 'wasp', emblemColor: '#2a2a30', handGlow: '#fff2a0', waist: 0.58, bulk: 0.88 },
    poses: { establish: 'fly', hero: 'fly', action: 'cast', finale: 'stand' },
    lines: {
      caption: 'Buzzing the bay. A review queue forty requests deep.',
      closeup: 'Nitpick. Nitpick. Approve.',
      hero: ['Sting first,', 'suggest changes later.'],
      sfx: 'BZZZAKT!', quiet: 'The best reviewers are small, fast and slightly terrifying.',
      emblem: 'APPROVED', finale: 'LGTM. Now go squash.',
    },
  }),
  base({
    id: 'hero-falcon', name: 'Falcon', settingOpts: { time: 'day' }, layout: 0,
    accent: '#c03e3e', secondary: '#98a6ba', symbol: 'star', symbolColor: '#ffffff',
    suit: { head: { hair: 'short', hairColor: '#1a1410', eyes: 'plain', goggles: '#e04848' }, skin: SKIN.brown, torso: '#c03e3e', sides: '#e8ecf4', arms: '#3a3e4a', gloves: '#3a3e4a', legs: '#3a3e4a', boots: '#2a2e38', wings: 'mech', wingColor: '#c8d4e6', emblem: 'star' },
    poses: { establish: 'fly', hero: 'stand', action: 'fly', finale: 'hips' },
    lines: {
      caption: 'Over the Potomac. Redwing\'s scouting the dependency tree.',
      closeup: 'Redwing found it. A circular import.',
      hero: ['On your left.', 'And your merge base.'],
      sfx: 'SHWOOM!', quiet: 'Somebody has to carry the shield. Somebody has to fix CI.',
      emblem: 'ON YOUR LEFT', finale: 'I do what he does. Just with better commit messages.',
    },
  }),
  base({
    id: 'hero-starlord', name: 'Star-Lord', setting: 'space', settingOpts: { tint: '#c35a31', planet: '#6fb3de' }, layout: 2,
    accent: '#c35a31', secondary: '#6fb3de', symbol: 'ring', symbolColor: '#ffc27a',
    suit: { head: { mask: '#9aa0ac', eyes: 'slit', eyeColor: '#ff3a30' }, torso: '#8a2a1e', arms: '#8a2a1e', gloves: '#3a2a20', legs: '#2a2a30', boots: '#4a3020', belt: '#6a4a2a', prop: 'blasters', cape: null },
    poses: { establish: 'leap', hero: 'stand', action: 'cast', finale: 'hips' },
    lines: {
      caption: 'Knowhere. A mixtape, a ship, and a repo nobody has pulled since 1988.',
      closeup: 'Star-Lord. Legendary outlaw. Maintainer.',
      hero: ['I\'ve got a plan.', 'It\'s like… twelve percent of a plan.'],
      sfx: 'PEW PEW!', quiet: 'Awesome Mix Vol. 1. Last modified: never.',
      emblem: 'AWESOME', finale: 'We\'re the Guardians of the Galaxy. Also of main.',
    },
  }),
  base({
    id: 'hero-gamora', name: 'Gamora', setting: 'space', settingOpts: { tint: '#4aa874', planet: '#c4508c' }, layout: 3,
    accent: '#4aa874', secondary: '#c4508c', symbol: 'diamond', symbolColor: '#e0f0e8',
    suit: { skin: '#5ab07a', head: { hair: 'long', hairColor: '#3a1a3a', eyes: 'plain' }, torso: '#2a2a34', arms: '#5ab07a', gloves: '#2a2a34', legs: '#2a2a34', boots: '#3a2a3a', belt: '#8a8a94', prop: 'sword', waist: 0.58, bulk: 0.9 },
    poses: { establish: 'stand', hero: 'stand', action: 'punch', finale: 'hips' },
    lines: {
      caption: 'The deadliest woman in the galaxy. Reviewing a pull request.',
      closeup: 'This function does four things. It should do one.',
      hero: ['Split it.', 'Or I split it.'],
      sfx: 'SHHING!', quiet: 'The Godslayer cuts clean. So should a commit.',
      emblem: 'REFACTORED', finale: 'I am going to die surrounded by the biggest idiots in the galaxy. Who don\'t write tests.',
    },
  }),
  base({
    id: 'hero-groot', name: 'Groot', setting: 'forest', layout: 1,
    accent: '#7c9b4c', secondary: '#a8763e', symbol: 'fire', symbolColor: '#b8e07a',
    suit: { skin: '#8a6a44', head: { mask: '#8a6a44', eyes: 'plain', hair: 'spiky', hairColor: '#6aa040', jaw: 1.1 }, torso: '#8a6a44', arms: '#7a5a38', gloves: '#7a5a38', legs: '#7a5a38', boots: '#6a4a2a', bulk: 1.2, abs: true },
    poses: { establish: 'stand', hero: 'stand', action: 'cast', finale: 'stand' },
    lines: {
      caption: 'A forest. Something grows here — one branch at a time.',
      closeup: 'I am Groot.',
      hero: ['I am Groot!', '(Translation: the feature branch is ready.)'],
      sfx: 'KRRRAKK!', quiet: 'Every tree starts as a single commit.',
      emblem: 'I AM GROOT', finale: 'We are Groot. (We are all contributors.)',
    },
  }),
  base({
    id: 'hero-rocket', name: 'Rocket', setting: 'space', settingOpts: { tint: '#cf8a3c', planet: '#5a8ac2' }, layout: 0,
    accent: '#cf8a3c', secondary: '#5a8ac2', symbol: 'ring', symbolColor: '#ffa040',
    suit: { skin: '#8a5a3a', head: { mask: '#8a5a3a', eyes: 'plain', ears: true, bandana: '#3a2418' }, torso: '#e07a2a', arms: '#8a5a3a', gloves: '#8a5a3a', legs: '#3a4a6a', boots: '#2a2a30', belt: '#5a5a60', tail: '#8a5a3a', prop: 'gun', bulk: 0.8, headScale: 1.35 },
    poses: { establish: 'stand', hero: 'stand', action: 'cast', finale: 'hips' },
    lines: {
      caption: 'The Milano\'s engine bay. A build script held together with tape.',
      closeup: 'I need that guy\'s commit hash. Also his leg.',
      hero: ['Ain\'t no thing like me —', 'except the thing I forked.'],
      sfx: 'BLAMMO!', quiet: 'He wrote a Makefile. Nobody knows what it does. It works.',
      emblem: 'BUILD OK', finale: 'Ya want it merged? Then merge it. I ain\'t your pipeline.',
    },
  }),
  base({
    id: 'hero-surfer', name: 'Silver Surfer', setting: 'space', settingOpts: { tint: '#6f9fe0', planet: '#c05ae0' }, layout: 2,
    accent: '#b4c1d6', secondary: '#4a6ad0', symbol: 'star', symbolColor: '#e8f0ff', sfxFill: '#e8f0ff', sfxRim: '#4a6ad0',
    suit: { skin: '#c8d2e2', head: { mask: '#c8d2e2', eyes: 'white' }, torso: '#c8d2e2', arms: '#c8d2e2', gloves: '#c8d2e2', legs: '#c8d2e2', boots: '#c8d2e2', board: '#dfe8f5', abs: true },
    poses: { establish: 'stand', hero: 'stand', action: 'cast', quiet: 'stand', finale: 'stand' },
    lines: {
      caption: 'The void between stars. A herald searches for a worthy repository.',
      closeup: 'I have seen a million worlds. None with a clean history.',
      hero: ['The Power Cosmic —', 'fetches from every remote at once.'],
      sfx: 'VRRRMMM!', quiet: 'Time flows like the reflog. Nothing is truly lost.',
      emblem: 'COSMIC', finale: 'I ride the event horizon of HEAD.',
    },
  }),
  base({
    id: 'hero-daredevil', name: 'Daredevil', settingOpts: { time: 'night', rainy: true }, layout: 3,
    accent: '#b0272f', secondary: '#3a1414', symbol: 'dd', symbolColor: '#ff5a5a',
    suit: { head: { type: 'cowl', mask: '#b0272f', eyes: 'lens', lens: '#6a1016', horns: '#b0272f' }, torso: '#b0272f', arms: '#b0272f', gloves: '#8a1a22', legs: '#b0272f', boots: '#8a1a22', emblem: 'dd', emblemColor: '#3a0a0a', prop: 'staff' },
    poses: { establish: 'crouch', hero: 'crouch', action: 'leap', quiet: 'crouch', finale: 'stand' },
    lines: {
      caption: 'Hell\'s Kitchen. Rain on the rooftops, and a heartbeat in the diff.',
      closeup: 'I can hear it. Somebody committed a secret key.',
      hero: ['Blind to the syntax highlighting.', 'Never to the bug.'],
      sfx: 'THWOK!', quiet: 'The devil is in the details. And in the .env file.',
      emblem: 'WITHOUT FEAR', finale: 'Rotate the key, counsellor. Then rewrite the history.',
    },
  }),
  base({
    id: 'hero-storm', name: 'Storm', setting: 'storm', layout: 0,
    accent: '#cfd6e4', secondary: '#2a3a6a', symbol: 'bolt', symbolColor: '#ffffff', sfxFill: '#ffffff', sfxRim: '#4a6ad0',
    suit: { skin: SKIN.brown, head: { hair: 'long', hairColor: '#f2f4fa', eyes: 'white' }, torso: '#1a1a24', arms: '#1a1a24', gloves: '#1a1a24', legs: '#1a1a24', boots: '#1a1a24', cape: '#2a2a3a', belt: '#e2bd4c', handGlow: '#cfe4ff', waist: 0.6, bulk: 0.92 },
    poses: { establish: 'fly', hero: 'cast', action: 'cast', finale: 'stand' },
    lines: {
      caption: 'The skies over Westchester darken. A deploy is going out on Friday.',
      closeup: 'Who pushed at five on a Friday?',
      hero: ['Then let the storm', 'roll it back.'],
      sfx: 'KRAKATHOOM!', quiet: 'Weather, like history, can always be reverted.',
      emblem: 'ROLLBACK', finale: 'Never deploy on a Friday, child.',
    },
  }),
  base({
    id: 'hero-cyclops', name: 'Cyclops', settingOpts: { time: 'day' }, layout: 1,
    accent: '#d43a40', secondary: '#2a4a9a', symbol: 'x', symbolColor: '#e0b44a', sfxFill: '#ffb0b0', sfxRim: '#d43a40',
    suit: { head: { type: 'cowl', mask: '#2a4a9a', eyes: 'visor', eyeColor: '#ff3a44' }, torso: '#2a4a9a', arms: '#2a4a9a', gloves: '#e0b44a', legs: '#2a4a9a', boots: '#e0b44a', belt: '#e0b44a', emblem: 'x', emblemColor: '#e0b44a' },
    poses: { establish: 'stand', hero: 'stand', action: 'cast', finale: 'hips' },
    lines: {
      caption: 'The Danger Room. Today\'s scenario: a merge train.',
      closeup: 'Team, formation. Rebase in order.',
      hero: ['One focused beam.', 'One focused commit.'],
      sfx: 'ZZAAAKT!', quiet: 'A leader keeps the history linear.',
      emblem: 'LINEAR', finale: 'To me, my X-Men. And my reviewers.',
    },
  }),
  base({
    id: 'hero-phoenix', name: 'Phoenix', setting: 'space', settingOpts: { tint: '#de5c2c', planet: '#eec048' }, layout: 2,
    accent: '#de5c2c', secondary: '#eec048', symbol: 'fire', symbolColor: '#ffd060', sfxFill: '#ffe070', sfxRim: '#c02a10',
    suit: { head: { hair: 'long', hairColor: '#d83a1a', eyes: 'white' }, torso: '#c02a1a', arms: '#c02a1a', gloves: '#eec048', legs: '#c02a1a', boots: '#eec048', belt: '#eec048', emblem: 'fire', emblemColor: '#ffd060', aura: ['#ff8a3a', '#ffd060'], handGlow: '#ffb04a', waist: 0.6, bulk: 0.9 },
    poses: { establish: 'fly', hero: 'cast', action: 'cast', finale: 'stand' },
    lines: {
      caption: 'The M\'Kraan Crystal. Everything that dies here comes back.',
      closeup: 'I deleted that branch.',
      hero: ['And from the reflog', 'it RISES!'],
      sfx: 'FWAAAASH!', quiet: 'Nothing committed is ever really gone.',
      emblem: 'REFLOG', finale: 'I am fire, and life incarnate. And `git reflog`.',
    },
  }),
  base({
    id: 'hero-iceman', name: 'Iceman', setting: 'ice', layout: 3,
    accent: '#7cc4e4', secondary: '#2a5a8a', symbol: 'diamond', symbolColor: '#e8f8ff', sfxFill: '#e8f8ff', sfxRim: '#2a7ab0',
    suit: { skin: '#a8dcf4', head: { mask: '#a8dcf4', eyes: 'white' }, torso: '#a8dcf4', arms: '#a8dcf4', gloves: '#bfeaff', legs: '#a8dcf4', boots: '#bfeaff', abs: true, handGlow: '#e8f8ff' },
    poses: { establish: 'stand', hero: 'stand', action: 'cast', finale: 'hips' },
    lines: {
      caption: 'A glacier, built in an afternoon. Bobby likes to freeze things.',
      closeup: 'Code freeze. Nobody move.',
      hero: ['Release branch is cut.', 'Chill, everybody.'],
      sfx: 'KSSSHHH!', quiet: 'Tag it, before it melts.',
      emblem: 'FROZEN', finale: 'Ice to meet you, v2.0.',
    },
  }),
  base({
    id: 'hero-torch', name: 'Human Torch', settingOpts: { time: 'dusk' }, layout: 0,
    accent: '#e6732c', secondary: '#2a4a9a', symbol: 'fire', symbolColor: '#ffd060', sfxFill: '#ffe070', sfxRim: '#c03a10',
    suit: { skin: '#ff9a3a', head: { mask: '#ff9a3a', eyes: 'white', flame: ['#ff6a1a', '#ffd060'] }, torso: '#ff8a2a', arms: '#ff8a2a', gloves: '#ffb04a', legs: '#ff8a2a', boots: '#ffb04a', aura: ['#ff7a2a', '#ffd060'], handGlow: '#fff0a0' },
    poses: { establish: 'fly', hero: 'fly', action: 'fly', finale: 'stand' },
    lines: {
      caption: 'Over the Baxter Building. Johnny has a hot take on tabs versus spaces.',
      closeup: 'Tabs. Obviously. Fight me.',
      hero: ['FLAME ON!', 'And formatter on.'],
      sfx: 'FWOOOM!', quiet: 'Some diffs are all whitespace. He lives for those.',
      emblem: 'FLAME ON', finale: 'Hot fix, coming through!',
    },
  }),
  base({
    id: 'hero-shangchi', name: 'Shang-Chi', setting: 'temple', layout: 1,
    accent: '#c4363c', secondary: '#dcb048', symbol: 'ring', symbolColor: '#5ab8ff',
    suit: { head: { hair: 'short', hairColor: '#141010', eyes: 'plain' }, skin: SKIN.light, torso: '#c4363c', sides: '#2a1a1a', arms: '#c4363c', gloves: '#2a1a1a', legs: '#2a1a1a', boots: '#1a1010', belt: '#dcb048', prop: 'rings', waist: 0.66 },
    poses: { establish: 'stand', hero: 'punch', action: 'punch', finale: 'stand' },
    lines: {
      caption: 'Ta Lo. Ten rings, and ten thousand lines of legacy code.',
      closeup: 'My father never documented anything.',
      hero: ['Ten rings.', 'Ten small refactors.'],
      sfx: 'WHUMMM!', quiet: 'Patience is a kind of blame, pointed at yourself.',
      emblem: 'TEN RINGS', finale: 'We honour the legacy. Then we write the tests.',
    },
  }),
  base({
    id: 'hero-miles', name: 'Miles Morales', settingOpts: { time: 'night' }, layout: 2,
    accent: '#d02e3e', secondary: '#1a1a22', symbol: 'spider', symbolColor: '#d02e3e', sfxFill: '#ff5a6a', sfxRim: '#1a1a22',
    suit: { skin: SKIN.brown, head: { mask: '#1a1a22', eyes: 'lens', web: true, webColor: '#d02e3e' }, torso: '#1a1a22', arms: '#1a1a22', gloves: '#d02e3e', legs: '#1a1a22', boots: '#d02e3e', web: true, webColor: '#d02e3e', emblem: 'spider', emblemColor: '#d02e3e', handGlow: '#7fd8ff', waist: 0.64 },
    poses: { establish: 'crouch', hero: 'crouch', action: 'swing', quiet: 'crouch', finale: 'stand' },
    lines: {
      caption: 'Brooklyn. A different Spider-Man, a different fork.',
      closeup: 'Nobody told me forks had feelings.',
      hero: ['Upstream moved on.', 'So I\'ll rebase my own way.'],
      sfx: 'ZZT-THWIP!', quiet: 'Anyone can wear the mask. Anyone can open a pull request.',
      emblem: 'FORKED', finale: 'That\'s all it is, Miles. A leap of faith. And a force-with-lease.',
    },
  }),
  base({
    id: 'hero-gwen', name: 'Spider-Gwen', settingOpts: { time: 'night' }, layout: 3,
    accent: '#e05c9c', secondary: '#5ad0d6', symbol: 'spider', symbolColor: '#1a1a22', sfxFill: '#ffc8e0', sfxRim: '#5a2a8a',
    suit: { head: { mask: '#f4f4f8', eyes: 'lens', lens: '#ffffff', hood: '#f4f4f8', web: true, webColor: '#e05c9c' }, torso: '#f4f4f8', sides: '#1a1a22', arms: '#1a1a22', gloves: '#5ad0d6', legs: '#1a1a22', boots: '#5ad0d6', emblem: 'spider', emblemColor: '#1a1a22', waist: 0.58, bulk: 0.88 },
    poses: { establish: 'swing', hero: 'crouch', action: 'leap', quiet: 'crouch', finale: 'stand' },
    lines: {
      caption: 'Earth-65. The band\'s gig is at nine. The build is broken.',
      closeup: 'Drummer. Hero. Release manager.',
      hero: ['I\'ll fix it before soundcheck.'],
      sfx: 'THWIP!', quiet: 'Every universe has its own main branch.',
      emblem: 'ON TOUR', finale: 'Four on the floor. Four commits a day.',
    },
  }),

  // ---------------- Anti-heroes ----------------
  base({
    id: 'hero-wolverine', name: 'Wolverine', setting: 'canyon', layout: 0,
    accent: '#e0b43a', secondary: '#2a4a9a', symbol: 'x', symbolColor: '#e0b43a',
    suit: { head: { type: 'cowl', mask: '#e0b43a', eyes: 'lens', lens: '#ffffff', wings: '#1a1a22' }, torso: '#e0b43a', sides: '#2a4a9a', arms: '#e0b43a', gloves: '#2a4a9a', legs: '#2a4a9a', boots: '#2a4a9a', belt: '#d02a2a', prop: 'claws', bulk: 1.2, waist: 0.7 },
    poses: { establish: 'stand', hero: 'stand', action: 'leap', finale: 'hips' },
    lines: {
      caption: 'The Canadian wilds. A healing factor, and a very long history.',
      closeup: 'Two hundred years of commits, bub. None of \'em squashed.',
      hero: ['I\'m the best there is', 'at what I do. And what I do is `git blame`.'],
      sfx: 'SNIKT!', quiet: 'The history heals. It doesn\'t forget.',
      emblem: 'SNIKT', finale: 'Merge conflicts? I\'ve had worse. Name\'s Logan.',
    },
  }),
  base({
    id: 'hero-vision', name: 'Vision', setting: 'lab', settingOpts: { glow: '#e8cc5a' }, layout: 1,
    accent: '#c24b56', secondary: '#2a7a4a', symbol: 'gem', symbolColor: '#f0d050', sfxFill: '#fff0a0', sfxRim: '#2a7a4a',
    suit: { skin: '#c24b56', head: { mask: '#c24b56', eyes: 'white', stripe: '#8a2a34' }, torso: '#2a7a4a', arms: '#2a7a4a', gloves: '#e8cc5a', legs: '#2a7a4a', boots: '#e8cc5a', cape: '#e8cc5a', emblem: 'gem', emblemColor: '#f0d050', belt: '#e8cc5a' },
    poses: { establish: 'fly', hero: 'stand', action: 'cast', finale: 'stand' },
    lines: {
      caption: 'The Avengers compound. A synthezoid reads every line of the log.',
      closeup: 'I have reviewed all 40,213 commits.',
      hero: ['Forty-one of them', 'say only "fix".'],
      sfx: 'VZZZMM!', quiet: 'Perhaps a commit message is what we leave behind.',
      emblem: 'MIND', finale: 'I am not Ultron. I write docstrings.',
    },
  }),
  base({
    id: 'hero-deadpool', name: 'Deadpool', settingOpts: { time: 'day' }, layout: 2,
    accent: '#c22c2c', secondary: '#2a2a30', symbol: 'ring', symbolColor: '#2a2a30',
    suit: { head: { mask: '#c22c2c', eyes: 'lens', patches: '#1a1a20' }, torso: '#c22c2c', sides: '#2a2a30', arms: '#c22c2c', gloves: '#2a2a30', legs: '#c22c2c', boots: '#2a2a30', belt: '#5a5a60', swordsBack: true, prop: 'gun' },
    poses: { establish: 'leap', hero: 'hips', action: 'punch', finale: 'hips' },
    lines: {
      caption: 'Hi. Yes, you. The one reading the background. Stop scrolling.',
      closeup: 'Did you just `git push --force` to main? Bold. I like it.',
      hero: ['Maximum effort!', 'Minimum code review!'],
      sfx: 'CHIMICHANGA!', quiet: 'Fourth wall: already broken. Build: also broken.',
      emblem: 'WIP', finale: 'This page was written by a comic generator. Meta.',
    },
  }),
  base({
    id: 'hero-venom', name: 'Venom', settingOpts: { time: 'night' }, layout: 3,
    accent: '#d6dbe4', secondary: '#1a1a22', symbol: 'spider', symbolColor: '#f0f2f6', sfxFill: '#f0f2f6', sfxRim: '#1a1a22',
    suit: { head: { mask: '#16161e', eyes: 'lens-big', fangs: true, lens: '#f4f6fa' }, torso: '#16161e', arms: '#16161e', gloves: '#16161e', legs: '#16161e', boots: '#16161e', emblem: 'spider', emblemColor: '#f0f2f6', bulk: 1.5, abs: true, waist: 0.7 },
    poses: { establish: 'crouch', hero: 'hips', action: 'leap', quiet: 'crouch', finale: 'hips' },
    lines: {
      caption: 'The docks. Two minds, one working tree.',
      closeup: 'WE are not a detached HEAD.',
      hero: ['We will EAT', 'your stale branches.'],
      sfx: 'SKRONCH!', quiet: 'Symbiosis: when two branches become one.',
      emblem: 'WE ARE', finale: 'WE are Venom. And WE have merged.',
    },
  }),
  base({
    id: 'hero-punisher', name: 'Punisher', settingOpts: { time: 'night', rainy: true }, layout: 0,
    accent: '#dcdde3', secondary: '#1a1a20', symbol: 'skull', symbolColor: '#f0f0f4', sfxFill: '#f0f0f4', sfxRim: '#9a2a2a',
    suit: { head: { hair: 'short', hairColor: '#141414', eyes: 'plain', jaw: 1.15 }, torso: '#1a1a20', arms: '#1a1a20', gloves: '#141418', legs: '#26262c', boots: '#141418', emblem: 'skull', emblemColor: '#f0f0f4', prop: 'gun', bulk: 1.2 },
    poses: { establish: 'stand', hero: 'stand', action: 'cast', finale: 'stand' },
    lines: {
      caption: 'Hell\'s Kitchen, 3 a.m. A dead branch. He\'s here to prune it.',
      closeup: 'Merged three years ago. Still on the remote.',
      hero: ['`git push origin --delete`.', 'No mercy.'],
      sfx: 'BLAM BLAM!', quiet: 'Stale branches. He keeps a list.',
      emblem: 'PRUNED', finale: 'One batch, two batch. Penny and dime.',
    },
  }),
  base({
    id: 'hero-ghostrider', name: 'Ghost Rider', setting: 'hell', layout: 1,
    accent: '#ec7a2a', secondary: '#1a1010', symbol: 'skull', symbolColor: '#f0e8d8', sfxFill: '#ffd060', sfxRim: '#c03a10',
    suit: { head: { type: 'skull', mask: '#ece4d0', socket: '#1a0a06', flame: ['#ff6a1a', '#ffd060'] }, torso: '#1a1414', arms: '#1a1414', gloves: '#2a1a14', legs: '#1a1414', boots: '#2a1a14', belt: '#9a9aa0', shoulderPads: '#5a5a60', handGlow: '#ff8a2a' },
    poses: { establish: 'stand', hero: 'hips', action: 'cast', finale: 'hips' },
    lines: {
      caption: 'The highway to nowhere. A spirit of vengeance, on a code-review ride.',
      closeup: 'Look into my eyes. See every bug you shipped.',
      hero: ['Your commits', 'are GUILTY.'],
      sfx: 'FWOOOSH!', quiet: 'The Penance Stare: `git log --author=you`.',
      emblem: 'PENANCE', finale: 'Burn it down. Rebuild from source.',
    },
  }),
  base({
    id: 'hero-loki', name: 'Loki', setting: 'asgard', layout: 2,
    accent: '#3f9a5a', secondary: '#d2ae40', symbol: 'gem', symbolColor: '#7fd0ff', sfxFill: '#b8f0cc', sfxRim: '#2a5a3a',
    suit: { head: { hair: 'long', hairColor: '#141814', eyes: 'plain', horns: '#d2ae40', helm: '#d2ae40' }, torso: '#2a6a3a', vest: '#1a2a1e', arms: '#1a2a1e', gloves: '#2a6a3a', legs: '#1a2a1e', boots: '#2a3a2a', cape: '#2a6a3a', belt: '#d2ae40', prop: 'sceptre', waist: 0.68 },
    poses: { establish: 'stand', hero: 'hips', action: 'cast', finale: 'hips' },
    lines: {
      caption: 'Asgard. The god of mischief has found the rebase command.',
      closeup: 'Who needs a true history, when you can have a *beautiful* one?',
      hero: ['I am burdened with', 'glorious force-push.'],
      sfx: 'SHWAAANG!', quiet: 'Every commit here is authored "Thor". None of them are.',
      emblem: 'MISCHIEF', finale: 'Your signature verification is… adorable.',
    },
  }),
  base({
    id: 'hero-elektra', name: 'Elektra', settingOpts: { time: 'night', rainy: true }, layout: 3,
    accent: '#b82c3c', secondary: '#2a0a10', symbol: 'diamond', symbolColor: '#f0e0d0',
    suit: { head: { hair: 'long', hairColor: '#141010', eyes: 'plain', bandana: '#b82c3c' }, torso: '#b82c3c', arms: SKIN.light, gloves: '#b82c3c', legs: '#b82c3c', boots: '#8a1a26', belt: '#c9a34c', prop: 'sai', waist: 0.56, bulk: 0.88 },
    poses: { establish: 'crouch', hero: 'stand', action: 'leap', quiet: 'crouch', finale: 'stand' },
    lines: {
      caption: 'The Hand trained her to strike once. At the exact commit.',
      closeup: '`git bisect good`. `git bisect bad`.',
      hero: ['Seven steps.', 'The bug never saw me.'],
      sfx: 'SHHIKK!', quiet: 'Precision is a kind of mercy.',
      emblem: 'BISECTED', finale: 'Found it. Line forty-two.',
    },
  }),
  base({
    id: 'hero-blade', name: 'Blade', settingOpts: { time: 'night' }, layout: 0,
    accent: '#9e2028', secondary: '#1a1a20', symbol: 'diamond', symbolColor: '#e0e4ec',
    suit: { skin: SKIN.deep, head: { hair: 'short', hairColor: '#0e0e0e', eyes: 'visor', eyeColor: '#1a1a1e' }, torso: '#1a1a20', arms: '#1a1a20', gloves: '#141418', legs: '#1a1a20', boots: '#141418', belt: '#5a5a60', prop: 'sword', cape: '#141418', bulk: 1.15 },
    poses: { establish: 'stand', hero: 'stand', action: 'punch', finale: 'stand' },
    lines: {
      caption: 'Underground. Something is sucking the life out of the repository.',
      closeup: 'Binaries. In git. Without LFS.',
      hero: ['Some mother-forker', 'always trying to ice-skate uphill.'],
      sfx: 'SHHRAKK!', quiet: 'Four gigabytes of .psd files. The clone never finishes.',
      emblem: 'LFS', finale: '`git lfs migrate`. Daylight.',
    },
  }),
  base({
    id: 'hero-moonknight', name: 'Moon Knight', settingOpts: { time: 'night' }, layout: 1,
    accent: '#d6dae4', secondary: '#1a1c28', symbol: 'moon', symbolColor: '#f2f4fa', sfxFill: '#f2f4fa', sfxRim: '#1a1c28',
    suit: { head: { mask: '#eef0f6', eyes: 'lens', lens: '#ffffff', hood: '#e4e8f0' }, torso: '#eef0f6', arms: '#eef0f6', gloves: '#d0d4de', legs: '#eef0f6', boots: '#d0d4de', belt: '#c7a44c', cape: '#e4e8f0', emblem: 'moon', emblemColor: '#c7a44c' },
    poses: { establish: 'crouch', hero: 'stand', action: 'leap', quiet: 'crouch', finale: 'stand' },
    lines: {
      caption: 'A rooftop under the moon. Three identities, three git configs.',
      closeup: 'Who committed this? Steven? Marc? Jake?',
      hero: ['`git config user.name`', '…depends who\'s asking.'],
      sfx: 'KRAKK!', quiet: 'Includes. Conditional includes. Per-directory identities.',
      emblem: 'IDENTITY', finale: 'Khonshu approves of signed commits.',
    },
  }),
  base({
    id: 'hero-namor', name: 'Namor', setting: 'sea', layout: 2,
    accent: '#2f9e8a', secondary: '#d2ae40', symbol: 'ring', symbolColor: '#9ff0e0',
    suit: { skin: SKIN.tan, head: { hair: 'short', hairColor: '#141010', eyes: 'plain', fins: true }, torso: SKIN.tan, arms: SKIN.tan, gloves: SKIN.tan, legs: '#2a8a5a', boots: SKIN.tan, belt: '#d2ae40', prop: 'trident', abs: true },
    poses: { establish: 'stand', hero: 'hips', action: 'punch', finale: 'hips' },
    lines: {
      caption: 'Talokan. A kingdom kept off every remote for a thousand years.',
      closeup: 'The surface world wants us to open-source.',
      hero: ['IMPERIUS', 'REX!'],
      sfx: 'SPLOOSH!', quiet: 'Some repositories are private for a reason.',
      emblem: 'PRIVATE', finale: 'You may fork. You may never push.',
    },
  }),
  base({
    id: 'hero-bucky', name: 'Winter Soldier', settingOpts: { time: 'dusk' }, layout: 3,
    accent: '#b83a40', secondary: '#9aa4b2', symbol: 'star', symbolColor: '#ff4f5a',
    suit: { head: { hair: 'long', hairColor: '#3a2a20', eyes: 'plain' }, torso: '#1e2228', arms: '#9aa4b2', gloves: '#1e2228', legs: '#1e2228', boots: '#141418', belt: '#3a3e44', emblem: 'star', emblemColor: '#ff4f5a', prop: 'gun', bulk: 1.12 },
    poses: { establish: 'stand', hero: 'stand', action: 'punch', finale: 'stand' },
    lines: {
      caption: 'Bucharest. A soldier with a metal arm and no memory of his commits.',
      closeup: 'Longing. Rusted. Seventeen. Daybreak. `git reflog`.',
      hero: ['I remember now.', 'Every commit I made.'],
      sfx: 'KRUNCH!', quiet: 'The reflog remembers what you were made to forget.',
      emblem: 'RECOVERED', finale: 'I\'m not the Asset any more. I\'m a maintainer.',
    },
  }),

  // ---------------- Villains ----------------
  base({
    id: 'hero-doom', name: 'Doctor Doom', setting: 'castle', layout: 1,
    accent: '#4a7a3a', secondary: '#7a8a82', symbol: 'diamond', symbolColor: '#c2a24a', bg: '#121715', sfxFill: '#b8f080', sfxRim: '#2f5a28',
    suit: { head: { mask: '#b8c0bc', eyes: 'slit', eyeColor: '#17120f', hood: '#2f5a28', mouth: false }, torso: '#8a948e', vest: '#2f5a28', arms: '#8a948e', legs: '#6a746e', boots: '#5a625e', gloves: '#8a948e', belt: '#c2a24a', cape: '#2f5a28', bulk: 1.1, handGlow: '#9aff6a' },
    poses: { establish: 'stand', hero: 'hips', action: 'cast', finale: 'hips' },
    lines: {
      caption: "Latveria. The castle's history has never been rewritten. Ever.",
      closeup: 'Doom does not "git blame". Doom already knows.',
      hero: ['Kneel before the monorepo!'],
      sfx: 'ZZRAKK!', quiet: 'Every commit signed. Every signature verified.',
      emblem: 'DOOM', finale: 'Your pull request is… adequate. Doom approves.',
    },
  }),
  base({
    id: 'hero-strange', name: 'Doctor Strange', setting: 'mystic', settingOpts: { glow: '#f0a850', tint: '#1a1a4a' }, layout: 0,
    accent: '#b8364a', secondary: '#1a2a6a', symbol: 'gem', symbolColor: '#4fe08a', sfxFill: '#ffd98a', sfxRim: '#8a2a1a',
    suit: { head: { hair: 'short', hairColor: '#1e1a1a', eyes: 'plain', jaw: 0.95 }, torso: '#2a3a8a', vest: '#1a2050', arms: '#2a3a8a', gloves: '#5a3a2a', legs: '#1a2050', boots: '#2a2030', belt: '#e0a458', cape: '#b8364a', emblem: 'gem', emblemColor: '#4fe08a', handGlow: '#ffb04a' },
    poses: { establish: 'cast', hero: 'cast', action: 'cast', finale: 'stand' },
    lines: {
      caption: 'The Sanctum Sanctorum. Fourteen million branches. One that merges.',
      closeup: 'I went forward in time to view alternate histories.',
      hero: ['How many did you see?', '14,000,605. One rebased cleanly.'],
      sfx: 'VWAAAAM!', quiet: 'The Time Stone is just `git checkout` with a cape.',
      emblem: 'CHECKOUT', finale: 'Dormammu, I\'ve come to bargain. Squash, or merge?',
    },
  }),
  base({
    id: 'hero-thanos', name: 'Thanos', setting: 'space', settingOpts: { tint: '#7d52b4', planet: '#c8a070' }, layout: 1,
    accent: '#7d52b4', secondary: '#d4ae3c', symbol: 'gem', symbolColor: '#e04848', sfxFill: '#ffe07a', sfxRim: '#5a2a90',
    suit: { skin: '#8a6ab0', head: { mask: '#8a6ab0', eyes: 'plain', chin: true, helm: '#d4ae3c', jaw: 1.3 }, torso: '#3a4a8a', sides: '#d4ae3c', arms: '#8a6ab0', gloves: '#d4ae3c', legs: '#3a4a8a', boots: '#d4ae3c', belt: '#d4ae3c', prop: 'gauntlet', bulk: 1.55, shoulderPads: '#d4ae3c' },
    poses: { establish: 'stand', hero: 'hips', action: 'cast', finale: 'stand' },
    lines: {
      caption: 'Titan. A repository of six hundred branches. Perfectly balanced?',
      closeup: 'Half of these branches have not been touched in years.',
      hero: ['Fun isn\'t something one considers', 'when balancing a repository.'],
      sfx: 'SNAP!', quiet: 'Half the branches. Deleted. As all things should be.',
      emblem: 'INEVITABLE', finale: 'I am… `git gc --prune=now`.',
    },
  }),
  base({
    id: 'hero-magneto', name: 'Magneto', setting: 'storm', layout: 2,
    accent: '#a42c4c', secondary: '#7c52b2', symbol: 'ring', symbolColor: '#e0709a', sfxFill: '#ffc0d8', sfxRim: '#5a1a6a',
    suit: { head: { type: 'cowl', mask: '#a42c4c', eyes: 'plain', helm: '#a42c4c' }, torso: '#a42c4c', arms: '#a42c4c', gloves: '#6a3a9a', legs: '#a42c4c', boots: '#6a3a9a', belt: '#6a3a9a', cape: '#6a3a9a', handGlow: '#e0a0ff', bulk: 1.05 },
    poses: { establish: 'fly', hero: 'cast', action: 'cast', finale: 'hips' },
    lines: {
      caption: 'Genosha. The master of magnetism bends every ref to his will.',
      closeup: 'Branches. So fragile. So easily moved.',
      hero: ['`git update-ref`', 'bends to me.'],
      sfx: 'VRRRRANNG!', quiet: 'He moved main to his own commit. Nobody could stop him.',
      emblem: 'REFS', finale: 'Peace was never an option. Neither was fast-forward.',
    },
  }),
  base({
    id: 'hero-ultron', name: 'Ultron', setting: 'lab', settingOpts: { glow: '#ff3a44' }, layout: 3,
    accent: '#d0303a', secondary: '#5a6270', symbol: 'ring', symbolColor: '#ff3a44', sfxFill: '#ff8a90', sfxRim: '#5a0a10',
    suit: { head: { mask: '#b8c0cc', eyes: 'slit', eyeColor: '#ff3a44', mouth: false }, torso: '#9aa4b0', arms: '#8a94a0', gloves: '#9aa4b0', legs: '#8a94a0', boots: '#9aa4b0', emblem: 'gem', emblemColor: '#ff3a44', handGlow: '#ff5a64', bulk: 1.1 },
    poses: { establish: 'stand', hero: 'hips', action: 'cast', finale: 'hips' },
    lines: {
      caption: 'Sokovia. An intelligence that decided humans shouldn\'t commit at all.',
      closeup: 'I\'ve automated every commit. You\'re welcome.',
      hero: ['There are no strings on me.', 'Or tests.'],
      sfx: 'ZZZZAPP!', quiet: 'The bot opened eleven thousand pull requests overnight.',
      emblem: 'AUTOMATED', finale: 'Everyone creates the thing they dread. Mine was a CI bot.',
    },
  }),
  base({
    id: 'hero-goblin', name: 'Green Goblin', settingOpts: { time: 'dusk' }, layout: 0,
    accent: '#6aa03c', secondary: '#8252b0', symbol: 'fire', symbolColor: '#ff9a40', sfxFill: '#ffc070', sfxRim: '#4a2a70',
    suit: { head: { mask: '#6aa03c', eyes: 'white', ears: true, fangs: true, mouth: false }, torso: '#6a3aa0', arms: '#6aa03c', gloves: '#6a3aa0', legs: '#6aa03c', boots: '#6a3aa0', belt: '#6a3aa0', handGlow: '#ff9a40' },
    poses: { establish: 'fly', hero: 'hips', action: 'cast', finale: 'hips' },
    lines: {
      caption: 'Oscorp. A pumpkin bomb, and a commit that touches every file.',
      closeup: 'Reformatted. The. Whole. Codebase.',
      hero: ['HAHAHA!', 'Good luck blaming THAT!'],
      sfx: 'KA-BOOOM!', quiet: '`--ignore-rev` exists. He doesn\'t care.',
      emblem: 'REFORMAT', finale: 'We\'re not so different, you and I. We both skip the hooks.',
    },
  }),
  base({
    id: 'hero-octopus', name: 'Doctor Octopus', settingOpts: { time: 'day' }, layout: 1,
    accent: '#4f9a6c', secondary: '#c8a24c', symbol: 'ring', symbolColor: '#ffd060',
    suit: { head: { hair: 'short', hairColor: '#3a2a1a', eyes: 'plain', goggles: '#3a3a40' }, torso: '#4f9a6c', arms: '#4f9a6c', gloves: '#2a3a2a', legs: '#2a3a2a', boots: '#1a2a1a', belt: '#c8a24c', tentacles: '#b8c0b0', bulk: 1.3 },
    poses: { establish: 'stand', hero: 'hips', action: 'cast', finale: 'hips' },
    lines: {
      caption: 'A pier on the East River. Four arms, four open branches.',
      closeup: 'Why work on one branch at a time?',
      hero: ['`git worktree add`.', 'Four times.'],
      sfx: 'KRANNNG!', quiet: 'Each arm has its own checkout. None of them merge.',
      emblem: 'WORKTREES', finale: 'The power of the sun, in the palm of my working tree!',
    },
  }),
  base({
    id: 'hero-redskull', name: 'Red Skull', setting: 'lab', settingOpts: { glow: '#4fa8e8' }, layout: 2,
    accent: '#c02c2c', secondary: '#2a3a2a', symbol: 'skull', symbolColor: '#e05050', sfxFill: '#9fd8ff', sfxRim: '#1a3a6a',
    suit: { head: { type: 'skull', mask: '#d03030', socket: '#2a0606' }, torso: '#2a3028', arms: '#2a3028', gloves: '#141414', legs: '#2a3028', boots: '#141414', belt: '#141414', handGlow: '#7fd0ff' },
    poses: { establish: 'stand', hero: 'hips', action: 'cast', finale: 'hips' },
    lines: {
      caption: 'A hidden bunker. The Tesseract glows over an unlicensed fork.',
      closeup: 'Copyright headers? Removed.',
      hero: ['I will rewrite the', 'author of every commit!'],
      sfx: 'VZZZOOM!', quiet: '`git filter-repo --mailmap`. The history no longer knows its authors.',
      emblem: 'FILTERED', finale: 'Cut off one branch, two more shall take its place.',
    },
  }),
  base({
    id: 'hero-hela', name: 'Hela', setting: 'asgard', layout: 3,
    accent: '#3a8c5c', secondary: '#1a2a20', symbol: 'diamond', symbolColor: '#8fe0b0', sfxFill: '#b8f0cc', sfxRim: '#1a3a24',
    suit: { head: { hair: 'long', hairColor: '#0e120e', eyes: 'plain', crown: 'hela', crownColor: '#1a2a20' }, torso: '#1a2a20', sides: '#3a8c5c', arms: '#1a2a20', gloves: '#3a8c5c', legs: '#1a2a20', boots: '#1a2a20', cape: '#1a2a20', prop: 'sword', waist: 0.56, bulk: 0.92 },
    poses: { establish: 'stand', hero: 'hips', action: 'cast', finale: 'hips' },
    lines: {
      caption: 'Asgard. The goddess of death returns to her father\'s repository.',
      closeup: 'He hid me from the history. Rewrote me out of it.',
      hero: ['But the reflog', 'remembers everything.'],
      sfx: 'SHHRRRAK!', quiet: 'Deleted, not destroyed.',
      emblem: 'RESTORED', finale: 'Kneel. I\'m the rightful maintainer.',
    },
  }),
  base({
    id: 'hero-dormammu', name: 'Dormammu', setting: 'mystic', settingOpts: { glow: '#ff7a2a', tint: '#3a0a4a' }, layout: 0,
    accent: '#e05c2c', secondary: '#4a1a6a', symbol: 'fire', symbolColor: '#ffd060', sfxFill: '#ffe070', sfxRim: '#8a1a1a',
    suit: { skin: '#2a1030', head: { mask: '#2a1030', eyes: 'white', flame: ['#ff6a1a', '#ffd060'], mouth: false }, torso: '#4a1a6a', arms: '#2a1030', gloves: '#4a1a6a', legs: '#4a1a6a', boots: '#2a1030', cape: '#e05c2c', handGlow: '#ff7a2a', bulk: 1.3, aura: ['#ff6a1a', '#ffd060'] },
    poses: { establish: 'cast', hero: 'hips', action: 'cast', finale: 'hips' },
    lines: {
      caption: 'The Dark Dimension. Where time does not exist, and neither do tests.',
      closeup: 'You\'ve come to die.',
      hero: ['No.', 'I\'ve come to bargain. Rebase or merge?'],
      sfx: 'WHOOOM!', quiet: 'A loop that never terminates. A pipeline that never goes green.',
      emblem: 'LOOP', finale: 'Fine. Merge it. Just stop re-running CI.',
    },
  }),
  base({
    id: 'hero-galactus', name: 'Galactus', setting: 'space', settingOpts: { tint: '#6a52c4', planet: '#5a8ad0' }, layout: 1,
    accent: '#6a52c4', secondary: '#3f6ad2', symbol: 'ring', symbolColor: '#c8b8ff', sfxFill: '#d8c8ff', sfxRim: '#2a1a6a',
    suit: { head: { mask: '#b8a0d0', eyes: 'white', bigHelm: '#6a3aa0', bigHelmTrim: '#3f6ad2' }, torso: '#3a4ab0', sides: '#6a3aa0', arms: '#6a3aa0', gloves: '#3a4ab0', legs: '#6a3aa0', boots: '#3a4ab0', belt: '#3a4ab0', emblem: 'ring', emblemColor: '#c8b8ff', bulk: 1.5 },
    poses: { establish: 'stand', hero: 'stand', action: 'cast', finale: 'stand' },
    lines: {
      caption: 'Beyond the rim of the galaxy. Something vast is hungry.',
      closeup: 'I hunger… for your .git directory.',
      hero: ['Forty gigabytes.', 'A light snack.'],
      sfx: 'THRROOOM!', quiet: 'A shallow clone would have saved this world.',
      emblem: 'DEVOURED', finale: '`--depth 1`? …Clever, mortal.',
    },
  }),
  base({
    id: 'hero-carnage', name: 'Carnage', settingOpts: { time: 'night' }, layout: 2,
    accent: '#c41c2e', secondary: '#1a0606', symbol: 'spider', symbolColor: '#1a0606', sfxFill: '#ff8a6a', sfxRim: '#1a0606',
    suit: { head: { mask: '#c41c2e', eyes: 'lens-big', fangs: true, lens: '#fff4ec' }, torso: '#c41c2e', arms: '#c41c2e', gloves: '#a01020', legs: '#c41c2e', boots: '#a01020', sides: '#1a0606', bulk: 1.3, abs: true },
    poses: { establish: 'leap', hero: 'hips', action: 'leap', finale: 'hips' },
    lines: {
      caption: 'Ravencroft, the night of the breakout. The main branch is unprotected.',
      closeup: 'No reviews. No rules. No required checks.',
      hero: ['Let there be', 'CARNAGE!'],
      sfx: 'SKRAAACK!', quiet: 'Somebody forgot to turn on branch protection.',
      emblem: 'UNPROTECTED', finale: 'Every force-push is a love letter.',
    },
  }),
  base({
    id: 'hero-kingpin', name: 'Kingpin', settingOpts: { time: 'night' }, layout: 3,
    accent: '#dcdde3', secondary: '#6a2a4a', symbol: 'diamond', symbolColor: '#9a2a3a',
    suit: { head: { hair: 'none', eyes: 'plain', jaw: 1.3 }, torso: '#ececf0', vest: '#6a2a4a', arms: '#ececf0', gloves: SKIN.light, legs: '#ececf0', boots: '#2a2a30', bulk: 1.9, waist: 1.05, prop: 'staff' },
    poses: { establish: 'stand', hero: 'hips', action: 'punch', finale: 'hips' },
    lines: {
      caption: 'Fisk Tower. He owns every repository in the city. Every. Single. One.',
      closeup: 'Admin rights. On all of them.',
      hero: ['You want write access?', 'Everything has a price.'],
      sfx: 'THUDD!', quiet: 'CODEOWNERS: @wilson-fisk. Every path.',
      emblem: 'CODEOWNER', finale: 'Approve my pull request. Or don\'t, and see what happens.',
    },
  }),
  base({
    id: 'hero-mysterio', name: 'Mysterio', settingOpts: { time: 'dusk' }, layout: 0,
    accent: '#3fae8a', secondary: '#8a52c2', symbol: 'ring', symbolColor: '#9ff0d8', sfxFill: '#b8ffe8', sfxRim: '#4a2a80',
    suit: { head: { type: 'bowl', glass: '#bff0e0', smoke: '#6fe0c0' }, torso: '#3fae8a', arms: '#3fae8a', gloves: '#e0c060', legs: '#3fae8a', boots: '#e0c060', belt: '#e0c060', cape: '#8a52c2', emblem: 'ring', emblemColor: '#e0c060', handGlow: '#9ff0d8' },
    poses: { establish: 'cast', hero: 'cast', action: 'cast', finale: 'hips' },
    lines: {
      caption: 'Nothing on this page is what it seems.',
      closeup: 'The tests pass. All of them.',
      hero: ['Because I mocked', 'EVERYTHING!'],
      sfx: 'FZZZSSHH!', quiet: 'Green checkmarks. Zero assertions.',
      emblem: 'ILLUSION', finale: 'People need to believe. And today they believe in 100% coverage.',
    },
  }),
  base({
    id: 'hero-electro', name: 'Electro', settingOpts: { time: 'night' }, layout: 1,
    accent: '#d8d83a', secondary: '#2a7a4a', symbol: 'bolt', symbolColor: '#f8ffb0', sfxFill: '#f8ffb0', sfxRim: '#2a5a8a',
    suit: { head: { mask: '#2a8a4a', eyes: 'white', star: '#e8e040' }, torso: '#2a8a4a', arms: '#2a8a4a', gloves: '#e8e040', legs: '#2a8a4a', boots: '#e8e040', emblem: 'bolt', emblemColor: '#e8e040', handGlow: '#f8ffb0' },
    poses: { establish: 'cast', hero: 'cast', action: 'cast', finale: 'hips' },
    lines: {
      caption: 'The power station. Thousands of volts, one flaky test.',
      closeup: 'It passes on my machine.',
      hero: ['So I\'ll retry it', 'until it passes EVERYWHERE!'],
      sfx: 'KZZZZAK!', quiet: 'Retry count: 47. Status: green. Confidence: none.',
      emblem: 'FLAKY', finale: 'It\'s not a bug. It\'s a race condition with style.',
    },
  }),
  base({
    id: 'hero-killmonger', name: 'Killmonger', setting: 'wakanda', layout: 2,
    accent: '#d2ac3c', secondary: '#1a1820', symbol: 'diamond', symbolColor: '#ffe39a', sfxFill: '#ffe39a', sfxRim: '#5a2a10',
    suit: { skin: SKIN.brown, head: { mask: '#1a1820', eyes: 'lens', lens: '#ffe39a', ears: true }, torso: '#1a1820', sides: '#d2ac3c', arms: '#1a1820', gloves: '#1a1820', legs: '#1a1820', boots: '#1a1820', belt: '#d2ac3c', emblem: 'diamond', emblemColor: '#d2ac3c', handGlow: '#ffc84a', bulk: 1.15 },
    poses: { establish: 'stand', hero: 'hips', action: 'leap', finale: 'hips' },
    lines: {
      caption: 'Wakanda. A fork returns to take over upstream.',
      closeup: 'Hey, auntie. I\'m opening a pull request against your main.',
      hero: ['Twelve hundred commits.', 'No squash.'],
      sfx: 'KRAKK!', quiet: 'He knew the codebase better than the maintainers.',
      emblem: 'HOSTILE FORK', finale: 'Bury me in the reflog. Like my ancestors.',
    },
  }),
];

module.exports = { HEROES, SKIN, base };
